Repository KEEPER31337/Homepage-Back-R2, pull requests merged in 2023-07, with the labels that each got.

#197 야구게임 추가요청사항 반영
  src/docs/asciidoc/game/baseball.adoc
  src/main/java/com/keeper/homepage/domain/game/api/GameController.kt
  src/main/java/com/keeper/homepage/domain/game/application/BaseballService.kt
  src/main/java/com/keeper/homepage/domain/game/dto/BaseballResult.kt
  src/main/java/com/keeper/homepage/domain/game/dto/req/BaseballGuessResponse.kt
  src/main/java/com/keeper/homepage/domain/game/dto/req/BaseballStartRequest.kt
  src/main/java/com/keeper/homepage/domain/game/dto/res/BaseballResponse.kt
  src/main/java/com/keeper/homepage/domain/game/dto/res/GameInfoByMemberResponse.kt
  src/main/java/com/keeper/homepage/domain/game/entity/redis/BaseballResultEntity.kt
  src/main/java/com/keeper/homepage/domain/game/support/BaseballSupport.kt
  src/test/java/com/keeper/homepage/domain/game/api/GameApiTestHelper.kt
  src/test/java/com/keeper/homepage/domain/game/api/GameControllerTest.kt
  src/test/java/com/keeper/homepage/domain/game/support/BaseballSupportTest.kt
Labels: 🚀 feature, ⭐️ backend

#201 Feature/회원 조회(검색) 기능구현
  src/docs/asciidoc/member/member.adoc
  src/docs/asciidoc/study/study.adoc
  src/main/java/com/keeper/homepage/domain/member/api/MemberController.java
  src/main/java/com/keeper/homepage/domain/member/application/MemberService.java
  src/main/java/com/keeper/homepage/domain/member/application/convenience/MemberFindService.java
  src/main/java/com/keeper/homepage/domain/member/dao/MemberRepository.java
  src/main/java/com/keeper/homepage/domain/member/dto/response/MemberResponse.java
  src/main/java/com/keeper/homepage/domain/study/application/StudyService.java
  src/main/java/com/keeper/homepage/domain/study/dto/response/StudyDetailResponse.java
  src/main/java/com/keeper/homepage/domain/study/entity/Study.java
  src/main/java/com/keeper/homepage/domain/study/entity/embedded/Link.java
  src/main/java/com/keeper/homepage/global/error/ErrorCode.java
  src/test/java/com/keeper/homepage/IntegrationTest.java
  src/test/java/com/keeper/homepage/domain/member/api/MemberControllerTest.java
  src/test/java/com/keeper/homepage/domain/study/api/StudyControllerTest.java
  src/test/java/com/keeper/homepage/domain/study/application/StudyServiceTest.java
Labels: 🚀 feature, ⭐️ backend, gpt review

#211 fix: 테스트 데이터 롤백 안되는 문제 해결
  src/test/java/com/keeper/homepage/domain/study/application/StudyServiceTest.java
Labels: ✅ test

#217 Feature/출석 + 출석 랭킹 기능 구현
  src/docs/asciidoc/attendance/attendance.adoc
  src/docs/asciidoc/keeper.adoc
  src/docs/asciidoc/post/post.adoc
  src/main/java/com/keeper/homepage/domain/attendance/api/AttendanceController.java
  src/main/java/com/keeper/homepage/domain/attendance/application/AttendanceService.java
  src/main/java/com/keeper/homepage/domain/attendance/application/BonusPoint.java
  src/main/java/com/keeper/homepage/domain/attendance/application/RankPoint.java
  src/main/java/com/keeper/homepage/domain/attendance/dao/AttendanceRepository.java
  src/main/java/com/keeper/homepage/domain/attendance/dto/response/AttendanceResponse.java
  src/main/java/com/keeper/homepage/domain/attendance/entity/Attendance.java
  src/main/java/com/keeper/homepage/domain/member/application/convenience/MemberFindService.java
  src/main/java/com/keeper/homepage/domain/member/dao/MemberRepository.java
  src/main/java/com/keeper/homepage/domain/member/entity/Member.java
  src/main/java/com/keeper/homepage/domain/point/application/PointLogService.java
  src/main/java/com/keeper/homepage/domain/point/dao/PointLogRepository.java
  src/main/java/com/keeper/homepage/domain/point/entity/PointLog.java
  src/main/java/com/keeper/homepage/global/error/ErrorCode.java
  src/main/java/com/keeper/homepage/global/util/redis/RedisUtil.java
  src/test/java/com/keeper/homepage/IntegrationTest.java
  src/test/java/com/keeper/homepage/domain/attendance/api/AttendanceControllerTest.java
  src/test/java/com/keeper/homepage/domain/attendance/application/AttendanceServiceTest.java
Labels: 🚀 feature, ✅ test, ⭐️ backend

#224 Feature/게시글 조회 api 스펙 변경
  src/main/java/com/keeper/homepage/domain/post/application/PostService.java
  src/main/java/com/keeper/homepage/domain/post/dao/PostRepository.java
  src/main/java/com/keeper/homepage/domain/post/dto/response/AdjacentPostResponse.java
  src/main/java/com/keeper/homepage/domain/post/dto/response/PostDetailResponse.java
  src/test/java/com/keeper/homepage/domain/post/api/PostControllerTest.java
  src/test/java/com/keeper/homepage/domain/post/application/PostServiceTest.java
Labels: ✅ test, ⭐️ backend

#213 Feature/#175 게임 랭킹 기능 구현
  src/docs/asciidoc/game/game.adoc
  src/main/java/com/keeper/homepage/domain/game/api/GameController.kt
  src/main/java/com/keeper/homepage/domain/game/application/GameFindService.kt
  src/main/java/com/keeper/homepage/domain/game/application/GameService.kt
  src/main/java/com/keeper/homepage/domain/game/dao/GameRepository.java
  src/main/java/com/keeper/homepage/domain/game/dto/res/GameRankResponse.kt
  src/main/java/com/keeper/homepage/domain/game/entity/embedded/Dice.java
  src/main/java/com/keeper/homepage/domain/game/entity/embedded/Lotto.java
  src/main/java/com/keeper/homepage/domain/game/entity/embedded/Roulette.java
  src/test/java/com/keeper/homepage/IntegrationTest.java
  src/test/java/com/keeper/homepage/domain/game/GameTestHelper.java
  src/test/java/com/keeper/homepage/domain/game/api/GameApiTestHelper.kt
  src/test/java/com/keeper/homepage/domain/game/api/GameControllerTest.kt
  src/test/java/com/keeper/homepage/domain/game/application/GameServiceTest.kt
Labels: 🚀 feature, ⭐️ backend

#223 Feature/임원진 목록 조회 & 직책 추가 삭제 기능 구현
  src/docs/asciidoc/keeper.adoc
  src/docs/asciidoc/library/book-manage.adoc
  src/docs/asciidoc/member/member-job.adoc
  src/docs/asciidoc/member/member.adoc
  src/main/java/com/keeper/homepage/domain/member/api/MemberController.java
  src/main/java/com/keeper/homepage/domain/member/api/MemberJobController.java
  src/main/java/com/keeper/homepage/domain/member/api/MemberRankController.java
  src/main/java/com/keeper/homepage/domain/member/application/MemberJobService.java
  src/main/java/com/keeper/homepage/domain/member/application/MemberRankService.java
  src/main/java/com/keeper/homepage/domain/member/application/MemberService.java
  src/main/java/com/keeper/homepage/domain/member/dto/response/JobResponse.java
  src/main/java/com/keeper/homepage/domain/member/dto/response/MemberJobResponse.java
  src/main/java/com/keeper/homepage/domain/member/entity/job/MemberJob.java
  src/main/java/com/keeper/homepage/global/error/ErrorCode.java
  src/test/java/com/keeper/homepage/IntegrationTest.java
  src/test/java/com/keeper/homepage/domain/member/api/MemberApiTestHelper.java
  src/test/java/com/keeper/homepage/domain/member/api/MemberControllerTest.java
  src/test/java/com/keeper/homepage/domain/member/api/MemberJobControllerTest.java
  src/test/java/com/keeper/homepage/domain/member/api/MemberRankControllerTest.java
  src/test/java/com/keeper/homepage/domain/member/application/MemberJobServiceTest.java
Labels: 🚀 feature, ✅ test, ⭐️ backend

#228 Feature/study + member_job db 변경 적용
  src/main/java/com/keeper/homepage/domain/member/entity/job/MemberJob.java
  src/main/java/com/keeper/homepage/domain/study/dto/request/StudyCreateRequest.java
  src/main/java/com/keeper/homepage/domain/study/dto/request/StudyUpdateRequest.java
  src/main/java/com/keeper/homepage/domain/study/dto/response/StudyDetailResponse.java
  src/main/java/com/keeper/homepage/domain/study/entity/Study.java
  src/main/java/com/keeper/homepage/domain/study/entity/embedded/Link.java
  src/main/java/com/keeper/homepage/domain/study/entity/embedded/NotionLink.java
  src/test/java/com/keeper/homepage/domain/study/StudyTestHelper.java
  src/test/java/com/keeper/homepage/domain/study/api/StudyControllerTest.java
Labels: ⭐️ backend, 🐬 DB

#230 docs: 이슈, PR 템플릿 추가 및 수정
  .github/ISSUE_TEMPLATE/bug-template.md
  .github/ISSUE_TEMPLATE/feature-template.md
  .github/ISSUE_TEMPLATE/issue-template.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 📄 docs

#232 Feature/세미나 출석 코드 입력 제한 + 최근의 세미나 조회 기능 구현
  src/docs/asciidoc/seminar/seminar-attendance.adoc
  src/docs/asciidoc/seminar/seminar.adoc
  src/main/java/com/keeper/homepage/domain/member/application/convenience/MemberFindService.java
  src/main/java/com/keeper/homepage/domain/member/dao/MemberRepository.java
  src/main/java/com/keeper/homepage/domain/seminar/api/SeminarAttendanceController.java
  src/main/java/com/keeper/homepage/domain/seminar/api/SeminarController.java
  src/main/java/com/keeper/homepage/domain/seminar/application/SeminarAttendanceService.java
  src/main/java/com/keeper/homepage/domain/seminar/application/SeminarService.java
  src/main/java/com/keeper/homepage/domain/seminar/application/convenience/ValidSeminarFindService.java
  src/main/java/com/keeper/homepage/domain/seminar/dao/SeminarRepository.java
  src/main/java/com/keeper/homepage/domain/seminar/dto/response/SeminarAttendanceResponse.java
  src/main/java/com/keeper/homepage/domain/seminar/dto/response/SeminarDetailResponse.java
  src/main/java/com/keeper/homepage/domain/seminar/entity/SeminarAttendance.java
  src/main/java/com/keeper/homepage/global/error/ErrorCode.java
  src/main/java/com/keeper/homepage/global/util/redis/RedisUtil.java
  src/test/java/com/keeper/homepage/IntegrationTest.java
  src/test/java/com/keeper/homepage/domain/member/MemberTestHelper.java
  src/test/java/com/keeper/homepage/domain/seminar/api/SeminarApiTestHelper.java
  src/test/java/com/keeper/homepage/domain/seminar/api/SeminarAttendanceControllerTest.java
  src/test/java/com/keeper/homepage/domain/seminar/api/SeminarControllerTest.java
  src/test/java/com/keeper/homepage/domain/seminar/application/SeminarAttendanceServiceTest.java
  src/test/java/com/keeper/homepage/domain/seminar/application/SeminarServiceTest.java
Labels: 🚀 feature, ⭐️ backend

#240 Feature/0724 db 변경사항 반영
  src/main/java/com/keeper/homepage/domain/member/entity/job/MemberJob.java
  src/main/java/com/keeper/homepage/domain/post/application/PostService.java
  src/main/java/com/keeper/homepage/domain/post/dto/response/PostDetailResponse.java
  src/main/java/com/keeper/homepage/domain/post/entity/category/Category.java
  src/test/java/com/keeper/homepage/domain/post/CategoryTestHelper.java
  src/test/java/com/keeper/homepage/domain/post/api/PostControllerTest.java
  src/test/java/com/keeper/homepage/domain/post/application/PostServiceTest.java
  src/test/java/com/keeper/homepage/domain/post/dao/category/CategoryRepositoryTest.java
Labels: ⭐️ backend, 🐬 DB

#241 Feature/게시글 요청 수정
  src/docs/asciidoc/post/post.adoc
  src/docs/asciidoc/study/study.adoc
  src/main/java/com/keeper/homepage/domain/post/api/PostController.java
  src/main/java/com/keeper/homepage/domain/post/application/PostService.java
  src/main/java/com/keeper/homepage/domain/post/dto/request/PostCreateRequest.java
  src/main/java/com/keeper/homepage/domain/post/dto/request/PostUpdateRequest.java
  src/main/java/com/keeper/homepage/domain/post/dto/response/PostDetailResponse.java
  src/main/java/com/keeper/homepage/domain/study/api/StudyController.java
  src/main/java/com/keeper/homepage/domain/study/dto/request/StudyCreateRequest.java
  src/main/java/com/keeper/homepage/global/error/ErrorCode.java
  src/test/java/com/keeper/homepage/domain/post/PostTestHelper.java
  src/test/java/com/keeper/homepage/domain/post/api/AdminPostControllerTest.java
  src/test/java/com/keeper/homepage/domain/post/api/PostApiTestHelper.java
  src/test/java/com/keeper/homepage/domain/post/api/PostControllerTest.java
  src/test/java/com/keeper/homepage/domain/post/application/PostServiceTest.java
  src/test/java/com/keeper/homepage/domain/post/dao/PostRepositoryTest.java
  src/test/java/com/keeper/homepage/domain/study/api/StudyApiTestHelper.java
  src/test/java/com/keeper/homepage/domain/study/api/StudyControllerTest.java
Labels: ⭐️ backend

#238 파일 포함 데이터 전달 시 requestBody로 전달하도록 변경
  src/docs/asciidoc/library/book-manage.adoc
  src/main/java/com/keeper/homepage/domain/library/api/BookManageController.kt
  src/main/java/com/keeper/homepage/domain/library/dto/req/BookRequest.kt
  src/test/java/com/keeper/homepage/domain/library/api/BookManageApiTestHelper.kt
  src/test/java/com/keeper/homepage/domain/library/api/BookManageControllerTest.kt
Labels: ⭐️ backend

#255 Feature/ctf team, contest entity repository 개발
  src/main/java/com/keeper/homepage/domain/ctf/dao/CtfContestRepository.java
  src/main/java/com/keeper/homepage/domain/ctf/dao/team/CtfTeamHasMemberRepository.java
  src/main/java/com/keeper/homepage/domain/ctf/dao/team/CtfTeamRepository.java
  src/main/java/com/keeper/homepage/domain/ctf/entity/CtfContest.java
  src/main/java/com/keeper/homepage/domain/ctf/entity/team/CtfTeam.java
  src/main/java/com/keeper/homepage/domain/ctf/entity/team/CtfTeamHasMember.java
  src/main/java/com/keeper/homepage/domain/ctf/entity/team/CtfTeamHasMemberPK.java
  src/main/java/com/keeper/homepage/domain/member/entity/Member.java
  src/test/java/com/keeper/homepage/IntegrationTest.java
  src/test/java/com/keeper/homepage/domain/ctf/CtfContestTestHelper.java
  src/test/java/com/keeper/homepage/domain/ctf/CtfTeamTestHelper.java
  src/test/java/com/keeper/homepage/domain/ctf/dao/CtfTeamRepositoryTest.java
Labels: 🚀 feature, ⭐️ backend
