Repository KEEPER31337/Homepage-Back-R2, pull requests merged in 2023-06, with the labels that each got.

#188 Feature/야구게임 get api 추가
  src/docs/asciidoc/game/baseball.adoc
  src/main/java/com/keeper/homepage/domain/game/api/GameController.kt
  src/main/java/com/keeper/homepage/domain/game/application/BaseballService.kt
  src/main/java/com/keeper/homepage/domain/game/dto/BaseballResult.kt
  src/main/java/com/keeper/homepage/domain/game/dto/req/BaseballGuessResponse.kt
  src/main/java/com/keeper/homepage/domain/game/support/BaseballSupport.kt
  src/test/java/com/keeper/homepage/domain/game/api/GameApiTestHelper.kt
  src/test/java/com/keeper/homepage/domain/game/api/GameControllerTest.kt
  src/test/java/com/keeper/homepage/domain/game/support/BaseballSupportTest.kt
Labels: 🚀 feature, ⭐️ backend

#190 Feature/#189 baseball response 스펙 변경
  src/docs/asciidoc/game/baseball.adoc
  src/main/java/com/keeper/homepage/domain/game/application/BaseballService.kt
  src/main/java/com/keeper/homepage/domain/game/dto/BaseballResult.kt
  src/main/java/com/keeper/homepage/domain/game/dto/req/BaseballGuessResponse.kt
  src/main/java/com/keeper/homepage/domain/game/support/BaseballSupport.kt
  src/test/java/com/keeper/homepage/domain/game/api/GameApiTestHelper.kt
  src/test/java/com/keeper/homepage/domain/game/api/GameControllerTest.kt
  src/test/java/com/keeper/homepage/domain/game/support/BaseballSupportTest.kt
Labels: 🚀 feature, ⭐️ backend

#184 feat : 도서 대출 신청 api 구현
  src/docs/asciidoc/library/book.adoc
  src/main/java/com/keeper/homepage/domain/library/api/BookController.java
  src/main/java/com/keeper/homepage/domain/library/application/BookService.java
  src/main/java/com/keeper/homepage/domain/library/dao/BookBorrowInfoRepository.java
  src/main/java/com/keeper/homepage/domain/member/entity/Member.java
  src/main/java/com/keeper/homepage/global/error/ErrorCode.java
  src/test/java/com/keeper/homepage/IntegrationTest.java
  src/test/java/com/keeper/homepage/domain/library/api/BookApiTestHelper.java
  src/test/java/com/keeper/homepage/domain/library/api/BookControllerTest.java
  src/test/java/com/keeper/homepage/domain/library/application/BookServiceTest.java
Labels: 🚀 feature, ⭐️ backend

#193 chore: gpt code review 설정
  .github/workflows/gpt_review.yml
Labels: ✏️ chore

#196 Feature/도서 대여 목록 조회 api
  src/docs/asciidoc/library/book.adoc
  src/main/java/com/keeper/homepage/domain/library/api/BookController.java
  src/main/java/com/keeper/homepage/domain/library/application/BookService.java
  src/main/java/com/keeper/homepage/domain/library/dao/BookBorrowInfoRepository.java
  src/main/java/com/keeper/homepage/domain/library/dto/resp/BookBorrowResponse.java
  src/main/java/com/keeper/homepage/domain/library/dto/resp/BookResponse.java
  src/test/java/com/keeper/homepage/domain/library/api/BookApiTestHelper.java
  src/test/java/com/keeper/homepage/domain/library/api/BookControllerTest.java
  src/test/java/com/keeper/homepage/domain/library/application/BookServiceTest.java
  src/test/java/com/keeper/homepage/global/restdocs/RestDocsHelper.java
Labels: 🚀 feature, ⭐️ backend, gpt review

#177 Feature/스터디 목록 조회 구현
  src/docs/asciidoc/study/study.adoc
  src/main/java/com/keeper/homepage/domain/member/entity/Member.java
  src/main/java/com/keeper/homepage/domain/study/api/StudyController.java
  src/main/java/com/keeper/homepage/domain/study/application/StudyService.java
  src/main/java/com/keeper/homepage/domain/study/dao/StudyRepository.java
  src/main/java/com/keeper/homepage/domain/study/dto/request/StudyCreateRequest.java
  src/main/java/com/keeper/homepage/domain/study/dto/response/StudyDetailResponse.java
  src/main/java/com/keeper/homepage/domain/study/dto/response/StudyListResponse.java
  src/main/java/com/keeper/homepage/domain/study/dto/response/StudyResponse.java
  src/main/java/com/keeper/homepage/domain/study/entity/Study.java
  src/main/java/com/keeper/homepage/domain/study/entity/embedded/GitLink.java
  src/main/java/com/keeper/homepage/domain/study/entity/embedded/Link.java
  src/main/java/com/keeper/homepage/domain/study/entity/embedded/NoteLink.java
  src/test/java/com/keeper/homepage/domain/study/StudyTestHelper.java
  src/test/java/com/keeper/homepage/domain/study/api/StudyApiTestHelper.java
  src/test/java/com/keeper/homepage/domain/study/api/StudyControllerTest.java
Labels: 🚀 feature, ✅ test, ⭐️ backend, gpt review
