Repository KEEPER31337/Homepage-Back-R2, pull requests merged in 2023-05, with the labels that each got.

#166 Feature/게시글 수정 썸네일 수정 api 분리
  src/docs/asciidoc/post/post.adoc
  src/main/java/com/keeper/homepage/domain/post/api/PostController.java
  src/main/java/com/keeper/homepage/domain/post/application/PostService.java
  src/main/java/com/keeper/homepage/domain/post/dto/request/PostUpdateRequest.java
  src/test/java/com/keeper/homepage/domain/post/api/PostApiTestHelper.java
  src/test/java/com/keeper/homepage/domain/post/api/PostControllerTest.java
  src/test/java/com/keeper/homepage/domain/post/application/PostServiceTest.java
Labels: 🚀 feature, ✅ test, ⭐️ backend

#167 Feature/스터디 추가 삭제 api 구현
  src/docs/asciidoc/keeper.adoc
  src/docs/asciidoc/study/study.adoc
  src/main/java/com/keeper/homepage/domain/member/entity/Member.java
  src/main/java/com/keeper/homepage/domain/post/dto/request/PostCreateRequest.java
  src/main/java/com/keeper/homepage/domain/post/dto/request/PostUpdateRequest.java
  src/main/java/com/keeper/homepage/domain/study/api/StudyController.java
  src/main/java/com/keeper/homepage/domain/study/application/StudyService.java
  src/main/java/com/keeper/homepage/domain/study/application/convenience/StudyFindService.java
  src/main/java/com/keeper/homepage/domain/study/dto/request/StudyCreateRequest.java
  src/main/java/com/keeper/homepage/domain/study/entity/Study.java
  src/main/java/com/keeper/homepage/global/error/ErrorCode.java
  src/test/java/com/keeper/homepage/IntegrationTest.java
  src/test/java/com/keeper/homepage/domain/post/api/PostControllerTest.java
  src/test/java/com/keeper/homepage/domain/study/api/StudyApiTestHelper.java
  src/test/java/com/keeper/homepage/domain/study/api/StudyControllerTest.java
Labels: 🚀 feature, ⭐️ backend

#168 Feature/활동조사 entity repository 개발
  src/main/java/com/keeper/homepage/domain/survey/converter/SurveyReplyTypeConverter.java
  src/main/java/com/keeper/homepage/domain/survey/dao/SurveyMemberReplyRepository.java
  src/main/java/com/keeper/homepage/domain/survey/dao/SurveyReplyExcuseRepository.java
  src/main/java/com/keeper/homepage/domain/survey/dao/SurveyReplyRepository.java
  src/main/java/com/keeper/homepage/domain/survey/dao/SurveyRepository.java
  src/main/java/com/keeper/homepage/domain/survey/entity/Survey.java
  src/main/java/com/keeper/homepage/domain/survey/entity/SurveyMemberReply.java
  src/main/java/com/keeper/homepage/domain/survey/entity/SurveyReply.java
  src/main/java/com/keeper/homepage/domain/survey/entity/SurveyReplyExcuse.java
  src/main/java/com/keeper/homepage/global/error/ErrorCode.java
  src/test/java/com/keeper/homepage/IntegrationTest.java
  src/test/java/com/keeper/homepage/domain/survey/SurveyMemberReplyTestHelper.java
  src/test/java/com/keeper/homepage/domain/survey/SurveyTestHelper.java
  src/test/java/com/keeper/homepage/domain/survey/dao/SurveyMemberReplyRepositoryTest.java
  src/test/java/com/keeper/homepage/domain/survey/dao/SurveyReplyRepositoryTest.java
  src/test/java/com/keeper/homepage/domain/survey/dao/SurveyRepositoryTest.java
Labels: 🚀 feature, ✅ test, ⭐️ backend

#181 #179 야구 게임 백엔드 제작
  src/docs/asciidoc/game/baseball.adoc
  src/docs/asciidoc/game/game.adoc
  src/docs/asciidoc/keeper.adoc
  src/main/java/com/keeper/homepage/domain/game/api/GameController.kt
  src/main/java/com/keeper/homepage/domain/game/application/BaseballService.kt
  src/main/java/com/keeper/homepage/domain/game/application/GameFindService.kt
  src/main/java/com/keeper/homepage/domain/game/dao/GameRepository.java
  src/main/java/com/keeper/homepage/domain/game/dto/BaseballResult.kt
  src/main/java/com/keeper/homepage/domain/game/dto/req/BaseballGuessRequest.kt
  src/main/java/com/keeper/homepage/domain/game/dto/req/BaseballGuessResponse.kt
  src/main/java/com/keeper/homepage/domain/game/dto/req/BaseballStartRequest.kt
  src/main/java/com/keeper/homepage/domain/game/entity/Game.java
  src/main/java/com/keeper/homepage/domain/game/entity/embedded/Baseball.java
  src/main/java/com/keeper/homepage/domain/game/support/BaseballSupport.kt
  src/main/java/com/keeper/homepage/domain/member/entity/Member.java
  src/main/java/com/keeper/homepage/global/config/security/filter/RefreshTokenFilter.java
  src/main/java/com/keeper/homepage/global/error/ErrorCode.java
  src/main/java/com/keeper/homepage/global/util/redis/RedisUtil.java
  src/test/java/com/keeper/homepage/IntegrationTest.java
  src/test/java/com/keeper/homepage/domain/auth/api/SignOutControllerTest.java
  src/test/java/com/keeper/homepage/domain/auth/api/test/AuthTestControllerTest.java
  src/test/java/com/keeper/homepage/domain/game/GameTestHelper.java
  src/test/java/com/keeper/homepage/domain/game/api/GameApiTestHelper.kt
  src/test/java/com/keeper/homepage/domain/game/api/GameControllerTest.kt
  src/test/java/com/keeper/homepage/domain/game/support/BaseballSupportTest.kt
  src/test/java/com/keeper/homepage/global/util/redis/RedisUtilTest.java
Labels: 🚀 feature, ⭐️ backend

#182 fix: api 문서 html 파일 안보이는 문제 해결
  src/docs/asciidoc/keeper.adoc
  src/docs/asciidoc/seminar/seminar.adoc
Labels: 📄 docs, ✏️ chore

#180 Feature/도서 목록 조회 구현
  src/main/java/com/keeper/homepage/domain/library/api/BookController.java
  src/main/java/com/keeper/homepage/domain/library/application/BookService.java
  src/main/java/com/keeper/homepage/domain/library/dao/BookRepository.java
  src/main/java/com/keeper/homepage/domain/library/dto/resp/BookResponse.java
  src/main/java/com/keeper/homepage/domain/library/entity/Book.java
  src/main/java/com/keeper/homepage/global/error/ErrorCode.java
  src/test/java/com/keeper/homepage/domain/library/api/BookApiTestHelper.java
  src/test/java/com/keeper/homepage/domain/library/api/BookControllerTest.java
Labels: 🚀 feature, ⭐️ backend

#178 Feature/포인트 랭킹 구현
  src/docs/asciidoc/member/member.adoc
  src/main/java/com/keeper/homepage/domain/member/api/MemberRankController.java
  src/main/java/com/keeper/homepage/domain/member/application/MemberRankService.java
  src/main/java/com/keeper/homepage/domain/member/dao/MemberRepository.java
  src/main/java/com/keeper/homepage/domain/member/dto/response/MemberPointRankResponse.java
  src/main/java/com/keeper/homepage/domain/member/entity/Member.java
  src/test/java/com/keeper/homepage/domain/member/api/MemberRankApiTestHelper.java
  src/test/java/com/keeper/homepage/domain/member/api/MemberRankControllerTest.java
  src/test/java/com/keeper/homepage/global/restdocs/RestDocsHelper.java
Labels: 🚀 feature, ⭐️ backend

#185 Feature/도서 api 작성 및 리팩토링
  src/docs/asciidoc/keeper.adoc
  src/docs/asciidoc/library/book.adoc
  src/main/java/com/keeper/homepage/domain/library/api/BookController.java
  src/main/java/com/keeper/homepage/domain/library/application/BookService.java
  src/main/java/com/keeper/homepage/domain/library/dao/BookRepository.java
  src/test/java/com/keeper/homepage/domain/library/api/BookApiTestHelper.java
  src/test/java/com/keeper/homepage/domain/library/api/BookControllerTest.java
  src/test/java/com/keeper/homepage/global/restdocs/RestDocsHelper.java
Labels: 🚀 feature, ⭐️ backend
