Repository KEEPER31337/Homepage-Back-R2, pull requests merged in 2023-09, with the labels that each got.

#345 Feature/#340 api 쿼리 카운터 구현
  build.gradle.kts
  src/main/java/com/keeper/homepage/global/util/aop/ApiStatistic.java
  src/main/java/com/keeper/homepage/global/util/aop/ApiStatisticAop.java
  src/main/java/com/keeper/homepage/global/util/aop/ConnectionProxyHandler.java
  src/main/java/com/keeper/homepage/global/util/aop/PreparedStatementProxyHandler.java
Labels: 🚀 feature, ⭐️ backend

#349 fix: 게시글 파일 다중 삭제 api로 변경
  src/docs/asciidoc/post/post.adoc
  src/main/java/com/keeper/homepage/domain/post/api/PostController.java
  src/main/java/com/keeper/homepage/domain/post/application/PostService.java
  src/main/java/com/keeper/homepage/domain/post/dto/request/PostFileDeleteRequest.java
  src/test/java/com/keeper/homepage/domain/post/api/PostApiTestHelper.java
  src/test/java/com/keeper/homepage/domain/post/api/PostControllerTest.java
  src/test/java/com/keeper/homepage/domain/post/application/PostServiceTest.java
Labels: ⭐️ backend

#351 Feature/도서 프론트 요청사항
  src/docs/asciidoc/library/book.adoc
  src/main/java/com/keeper/homepage/domain/library/api/BookController.java
  src/main/java/com/keeper/homepage/domain/library/application/BookBorrowInfoFindService.java
  src/main/java/com/keeper/homepage/domain/library/application/BookService.java
  src/main/java/com/keeper/homepage/domain/library/dao/BookBorrowInfoRepository.java
  src/main/java/com/keeper/homepage/domain/library/dto/resp/BookBorrowResponse.java
  src/main/java/com/keeper/homepage/domain/library/entity/BookBorrowInfo.java
  src/main/java/com/keeper/homepage/domain/member/entity/Member.java
  src/main/java/com/keeper/homepage/global/error/ErrorCode.java
  src/test/java/com/keeper/homepage/domain/library/api/BookApiTestHelper.java
  src/test/java/com/keeper/homepage/domain/library/api/BookControllerTest.java
  src/test/java/com/keeper/homepage/domain/library/application/BookServiceTest.java
Labels: ⭐️ backend

#352 Feature/족보 게시글 관련 처리
  src/docs/asciidoc/post/post.adoc
  src/main/java/com/keeper/homepage/domain/post/application/PostService.java
  src/main/java/com/keeper/homepage/domain/post/dto/response/PostDetailResponse.java
  src/main/java/com/keeper/homepage/domain/post/dto/response/PostResponse.java
  src/test/java/com/keeper/homepage/domain/post/api/PostApiTestHelper.java
  src/test/java/com/keeper/homepage/domain/post/api/PostControllerTest.java
  src/test/java/com/keeper/homepage/domain/post/application/PostServiceTest.java
Labels: ⭐️ backend

#353 fix: mask-password option 추가
  .github/workflows/deploy-development.yml
Labels: 🐞 bug

#350 Feature/회원 탈퇴 기능
  src/docs/asciidoc/member/member.adoc
  src/main/java/com/keeper/homepage/domain/member/api/MemberController.java
  src/main/java/com/keeper/homepage/domain/member/application/MemberProfileService.java
  src/main/java/com/keeper/homepage/domain/member/application/MemberService.java
  src/main/java/com/keeper/homepage/domain/member/dto/request/DeleteMemberRequest.java
  src/main/java/com/keeper/homepage/domain/member/entity/Member.java
  src/main/java/com/keeper/homepage/domain/member/entity/embedded/Profile.java
  src/main/java/com/keeper/homepage/global/error/ErrorCode.java
  src/test/java/com/keeper/homepage/domain/member/api/MemberControllerTest.java
  src/test/java/com/keeper/homepage/domain/member/application/MemberServiceTest.java
Labels: ⭐️ backend

#341 Feature/세미나 수정사항
  src/docs/asciidoc/seminar/seminar-attendance.adoc
  src/docs/asciidoc/seminar/seminar.adoc
  src/main/java/com/keeper/homepage/domain/member/application/convenience/MemberFindService.java
  src/main/java/com/keeper/homepage/domain/member/dao/MemberRepository.java
  src/main/java/com/keeper/homepage/domain/seminar/api/SeminarAttendanceController.java
  src/main/java/com/keeper/homepage/domain/seminar/api/SeminarController.java
  src/main/java/com/keeper/homepage/domain/seminar/application/SeminarAttendanceService.java
  src/main/java/com/keeper/homepage/domain/seminar/application/SeminarService.java
  src/main/java/com/keeper/homepage/domain/seminar/dao/SeminarAttendanceRepository.java
  src/main/java/com/keeper/homepage/domain/seminar/dao/SeminarRepository.java
  src/main/java/com/keeper/homepage/domain/seminar/dto/response/SeminarAttendanceDetailResponse.java
  src/main/java/com/keeper/homepage/domain/seminar/dto/response/SeminarAttendanceManageResponse.java
  src/main/java/com/keeper/homepage/domain/seminar/dto/response/SeminarDetailResponse.java
  src/main/java/com/keeper/homepage/domain/seminar/entity/Seminar.java
  src/main/java/com/keeper/homepage/global/error/ErrorCode.java
  src/main/java/com/keeper/homepage/global/util/semester/SemesterUtil.java
  src/test/java/com/keeper/homepage/domain/seminar/api/SeminarApiTestHelper.java
  src/test/java/com/keeper/homepage/domain/seminar/api/SeminarAttendanceControllerTest.java
  src/test/java/com/keeper/homepage/domain/seminar/api/SeminarControllerTest.java
  src/test/java/com/keeper/homepage/domain/seminar/application/SeminarAttendanceServiceTest.java
  src/test/java/com/keeper/homepage/domain/seminar/application/SeminarServiceTest.java
Labels: 🚀 feature, ⭐️ backend, 🐬 DB

#357 Feature/출석 백엔드에서 처리
  src/docs/asciidoc/attendance/attendance.adoc
  src/main/java/com/keeper/homepage/domain/attendance/api/AttendanceController.java
  src/main/java/com/keeper/homepage/domain/attendance/application/AttendanceService.java
  src/main/java/com/keeper/homepage/domain/post/application/PostService.java
  src/main/java/com/keeper/homepage/domain/post/entity/Post.java
  src/main/java/com/keeper/homepage/global/config/interceptor/AttendanceInterceptor.java
  src/main/java/com/keeper/homepage/global/config/web/WebMvcConfiguration.java
  src/main/java/com/keeper/homepage/global/error/ErrorCode.java
  src/test/java/com/keeper/homepage/domain/attendance/api/AttendanceControllerTest.java
  src/test/java/com/keeper/homepage/domain/attendance/application/AttendanceServiceTest.java
Labels: 🚀 feature, ⭐️ backend

#356 Feature/회원 프로필 조회 수정
  src/main/java/com/keeper/homepage/domain/member/api/MemberController.java
  src/main/java/com/keeper/homepage/domain/member/application/MemberProfileService.java
  src/main/java/com/keeper/homepage/domain/member/application/MemberService.java
  src/main/java/com/keeper/homepage/domain/member/dao/MemberRepository.java
  src/main/java/com/keeper/homepage/domain/member/dao/friend/FriendRepository.java
  src/main/java/com/keeper/homepage/domain/member/dto/request/DeleteMemberRequest.java
  src/main/java/com/keeper/homepage/domain/member/dto/response/profile/MemberFriendResponse.java
  src/main/java/com/keeper/homepage/domain/member/dto/response/profile/MemberProfileResponse.java
  src/main/java/com/keeper/homepage/domain/member/entity/Member.java
  src/main/java/com/keeper/homepage/domain/member/entity/embedded/Profile.java
  src/test/java/com/keeper/homepage/domain/member/api/MemberApiTestHelper.java
  src/test/java/com/keeper/homepage/domain/member/api/MemberControllerTest.java
  src/test/java/com/keeper/homepage/domain/member/application/MemberProfileServiceTest.java
  src/test/java/com/keeper/homepage/domain/member/application/MemberServiceTest.java
Labels: 🐞 bug, ⭐️ backend

#362 Feature/default batch fetch size 적용
  src/main/java/com/keeper/homepage/domain/member/entity/Member.java
  src/main/resources/config/application.yml
Labels: ✏️ chore

#355 Feature/상벌점 기능 추가 및 버그 수정
  src/docs/asciidoc/merit/merit.adoc
  src/main/java/com/keeper/homepage/domain/merit/api/MeritController.java
  src/main/java/com/keeper/homepage/domain/merit/application/MeritLogService.java
  src/main/java/com/keeper/homepage/domain/merit/application/MeritTypeService.java
  src/main/java/com/keeper/homepage/domain/merit/dao/MeritLogRepository.java
  src/main/java/com/keeper/homepage/domain/merit/dto/request/AddMeritTypeRequest.java
  src/main/java/com/keeper/homepage/domain/merit/dto/request/SearchMeritLogListRequest.java
  src/main/java/com/keeper/homepage/domain/merit/dto/request/UpdateMeritTypeRequest.java
  src/main/java/com/keeper/homepage/domain/merit/dto/response/MeritTypeResponse.java
  src/main/java/com/keeper/homepage/domain/merit/dto/response/SearchMemberMeritLogResponse.java
  src/main/java/com/keeper/homepage/domain/merit/dto/response/SearchMeritLogListResponse.java
  src/main/java/com/keeper/homepage/domain/merit/entity/MeritType.java
  src/main/java/com/keeper/homepage/global/error/ErrorCode.java
  src/test/java/com/keeper/homepage/domain/merit/MeritTypeHelper.java
  src/test/java/com/keeper/homepage/domain/merit/api/MeritApiTestHelper.java
  src/test/java/com/keeper/homepage/domain/merit/api/MeritControllerTest.java
  src/test/java/com/keeper/homepage/domain/merit/application/MeritLogServiceTest.java
  src/test/java/com/keeper/homepage/domain/merit/application/MeritTypeServiceTest.java
  src/test/java/com/keeper/homepage/domain/merit/dao/MeritLogRepositoryTest.java
Labels: 🐞 bug, 🚀 feature, ⭐️ backend

#364 Feature/대출 현황 가져오기 수정
  src/main/java/com/keeper/homepage/domain/library/application/BorrowManageService.kt
  src/main/java/com/keeper/homepage/domain/library/dao/BookBorrowLogRepository.java
  src/main/java/com/keeper/homepage/domain/library/dto/resp/BorrowLogResponse.kt
  src/main/java/com/keeper/homepage/domain/library/entity/BookBorrowLog.java
  src/test/java/com/keeper/homepage/domain/library/api/BookManageApiTestHelper.kt
  src/test/java/com/keeper/homepage/domain/library/api/BorrowManageControllerTest.kt
Labels: ⭐️ backend

#368 fix: RequestBody를 queryParam으로 수정 및 테스트 코드 추가
  src/main/java/com/keeper/homepage/domain/merit/api/MeritController.java
  src/main/java/com/keeper/homepage/domain/merit/dao/MeritLogRepository.java
  src/test/java/com/keeper/homepage/domain/merit/api/MeritControllerTest.java
  src/test/java/com/keeper/homepage/domain/merit/application/MeritLogServiceTest.java
Labels: 🐞 bug, ✅ test, ⭐️ backend

#366 Feature/회원 탈퇴 기능 수정 및 관리자용 탈퇴 api 구현
  src/docs/asciidoc/member/member.adoc
  src/main/java/com/keeper/homepage/domain/comment/dao/CommentRepository.java
  src/main/java/com/keeper/homepage/domain/ctf/dao/CtfContestRepository.java
  src/main/java/com/keeper/homepage/domain/ctf/dao/challenge/CtfChallengeRepository.java
  src/main/java/com/keeper/homepage/domain/ctf/dao/team/CtfTeamRepository.java
  src/main/java/com/keeper/homepage/domain/ctf/entity/CtfContest.java
  src/main/java/com/keeper/homepage/domain/ctf/entity/challenge/CtfChallenge.java
  src/main/java/com/keeper/homepage/domain/ctf/entity/team/CtfTeam.java
  src/main/java/com/keeper/homepage/domain/election/dao/ElectionRepository.java
  src/main/java/com/keeper/homepage/domain/election/entity/Election.java
  src/main/java/com/keeper/homepage/domain/game/dao/GameRepository.java
  src/main/java/com/keeper/homepage/domain/member/api/MemberController.java
  src/main/java/com/keeper/homepage/domain/member/application/MemberService.java
  src/main/java/com/keeper/homepage/domain/member/application/convenience/MemberDeleteService.java
  src/main/java/com/keeper/homepage/domain/member/dao/comment/MemberHasCommentDislikeRepository.java
  src/main/java/com/keeper/homepage/domain/member/dao/comment/MemberHasCommentLikeRepository.java
  src/main/java/com/keeper/homepage/domain/member/dao/friend/FriendRepository.java
  src/main/java/com/keeper/homepage/domain/member/dao/post/MemberHasPostDislikeRepository.java
  src/main/java/com/keeper/homepage/domain/member/dao/post/MemberHasPostLikeRepository.java
  src/main/java/com/keeper/homepage/domain/member/dao/post/MemberReadPostRepository.java
  src/main/java/com/keeper/homepage/domain/member/dto/request/AdminDeleteMemberRequest.java
  src/main/java/com/keeper/homepage/domain/member/entity/Member.java
  src/main/java/com/keeper/homepage/domain/member/entity/embedded/Profile.java
  src/main/java/com/keeper/homepage/domain/member/entity/type/MemberType.java
  src/main/java/com/keeper/homepage/domain/post/dao/PostRepository.java
  src/main/java/com/keeper/homepage/domain/post/entity/Post.java
  src/main/java/com/keeper/homepage/domain/seminar/dao/SeminarRepository.java
  src/main/java/com/keeper/homepage/domain/study/dao/StudyRepository.java
  src/main/java/com/keeper/homepage/domain/study/entity/Study.java
  src/test/java/com/keeper/homepage/IntegrationTest.java
  src/test/java/com/keeper/homepage/domain/member/api/MemberControllerTest.java
  src/test/java/com/keeper/homepage/domain/member/application/MemberServiceTest.java
Labels: 🚀 feature, ⭐️ backend

#369 fix: 출석 순위 버그 수정
  src/main/java/com/keeper/homepage/global/config/interceptor/AttendanceInterceptor.java
Labels: 🐞 bug, ⭐️ backend
