Repository KEEPER31337/Homepage-Back-R2, pull requests merged in 2023-03, with the labels that each got.

#111 Feature/Game 관련 entity repository생성
  src/main/java/com/keeper/homepage/domain/game/dao/GameRepository.java
  src/main/java/com/keeper/homepage/domain/game/entity/Game.java
  src/main/java/com/keeper/homepage/domain/game/entity/embedded/Dice.java
  src/main/java/com/keeper/homepage/domain/game/entity/embedded/Lotto.java
  src/main/java/com/keeper/homepage/domain/game/entity/embedded/Roulette.java
  src/test/java/com/keeper/homepage/IntegrationTest.java
  src/test/java/com/keeper/homepage/domain/game/GameTestHelper.java
  src/test/java/com/keeper/homepage/domain/game/dao/GameRepositoryTest.java
Labels: 🚀 feature, ⭐️ backend

#116 Feature/book 관련 entity repository 생성
  src/main/java/com/keeper/homepage/domain/library/converter/BookBorrowStatusTypeConverter.java
  src/main/java/com/keeper/homepage/domain/library/converter/BookDepartmentTypeConverter.java
  src/main/java/com/keeper/homepage/domain/library/dao/BookBorrowInfoRepository.java
  src/main/java/com/keeper/homepage/domain/library/dao/BookBorrowStatusRepository.java
  src/main/java/com/keeper/homepage/domain/library/dao/BookDepartmentRepository.java
  src/main/java/com/keeper/homepage/domain/library/dao/BookRepository.java
  src/main/java/com/keeper/homepage/domain/library/entity/Book.java
  src/main/java/com/keeper/homepage/domain/library/entity/BookBorrowInfo.java
  src/main/java/com/keeper/homepage/domain/library/entity/BookBorrowStatus.java
  src/main/java/com/keeper/homepage/domain/library/entity/BookDepartment.java
  src/main/java/com/keeper/homepage/domain/member/entity/Member.java
  src/main/java/com/keeper/homepage/global/error/ErrorCode.java
  src/test/java/com/keeper/homepage/IntegrationTest.java
  src/test/java/com/keeper/homepage/domain/library/BookBorrowInfoTestHelper.java
  src/test/java/com/keeper/homepage/domain/library/BookTestHelper.java
  src/test/java/com/keeper/homepage/domain/library/dao/BookRepositoryTest.java
Labels: 🚀 feature, ⭐️ backend

#134 Feature/#133 코틀린 설정 적용
  build.gradle
  build.gradle.kts
  settings.gradle
  settings.gradle.kts
Labels: ✏️ chore, ⭐️ backend

#145 Feature/#140 도서 추가 기능
  build.gradle.kts
  src/docs/asciidoc/keeper.adoc
  src/docs/asciidoc/library/book-manage.adoc
  src/main/java/com/keeper/homepage/domain/library/api/BookManageController.kt
  src/main/java/com/keeper/homepage/domain/library/application/BookManageService.kt
  src/main/java/com/keeper/homepage/domain/library/converter/BookDepartmentTypeConverter.java
  src/main/java/com/keeper/homepage/domain/library/dto/req/AddBookRequest.kt
  src/main/java/com/keeper/homepage/domain/library/entity/Book.java
  src/main/java/com/keeper/homepage/global/config/web/WebMvcConfiguration.java
  src/test/java/com/keeper/homepage/IntegrationTest.java
  src/test/java/com/keeper/homepage/domain/library/api/BookManageApiTestHelper.kt
  src/test/java/com/keeper/homepage/domain/library/api/BookManageControllerTest.kt
Labels: 🚀 feature, ⭐️ backend

#147 Feature/게시글 좋아요 싫어요 기능구현
  src/docs/asciidoc/post/post.adoc
  src/main/java/com/keeper/homepage/domain/member/entity/Member.java
  src/main/java/com/keeper/homepage/domain/post/api/PostController.java
  src/main/java/com/keeper/homepage/domain/post/application/PostService.java
  src/test/java/com/keeper/homepage/domain/post/api/PostApiTestHelper.java
  src/test/java/com/keeper/homepage/domain/post/api/PostControllerTest.java
  src/test/java/com/keeper/homepage/domain/post/application/PostServiceTest.java
Labels: 🚀 feature, ✅ test, ⭐️ backend

#148 Feature/#141 도서 삭제 기능
  src/docs/asciidoc/library/book-manage.adoc
  src/main/java/com/keeper/homepage/domain/library/api/BookManageController.kt
  src/main/java/com/keeper/homepage/domain/library/application/BookManageService.kt
  src/main/java/com/keeper/homepage/domain/library/entity/Book.java
  src/main/java/com/keeper/homepage/domain/library/entity/BookBorrowInfo.java
  src/main/java/com/keeper/homepage/domain/library/entity/BookBorrowStatus.java
  src/main/java/com/keeper/homepage/domain/library/entity/BookDepartment.java
  src/main/java/com/keeper/homepage/global/error/ErrorCode.java
  src/test/java/com/keeper/homepage/domain/library/api/BookManageApiTestHelper.kt
  src/test/java/com/keeper/homepage/domain/library/api/BookManageControllerTest.kt
  src/test/java/com/keeper/homepage/domain/library/application/BookManageServiceTest.kt
Labels: 🚀 feature, ⭐️ backend

#149 Feature/#136 대출신청도서 조회
  src/docs/asciidoc/library/book-manage.adoc
  src/main/java/com/keeper/homepage/domain/library/api/BorrowManageController.kt
  src/main/java/com/keeper/homepage/domain/library/application/BorrowManageService.kt
  src/main/java/com/keeper/homepage/domain/library/dao/BookBorrowInfoRepository.java
  src/main/java/com/keeper/homepage/domain/library/dto/resp/BorrowResponse.kt
  src/main/java/com/keeper/homepage/domain/member/entity/Member.java
  src/main/java/com/keeper/homepage/global/error/ExceptionAdvice.java
  src/test/java/com/keeper/homepage/domain/library/BookBorrowInfoTestHelper.java
  src/test/java/com/keeper/homepage/domain/library/api/BookManageApiTestHelper.kt
  src/test/java/com/keeper/homepage/domain/library/api/BorrowManageApiTestHelper.kt
  src/test/java/com/keeper/homepage/domain/library/api/BorrowManageControllerTest.kt
Labels: 🚀 feature, ⭐️ backend

#150 Feature/#137 대출 승인 거부 기능
  src/docs/asciidoc/library/book-manage.adoc
  src/main/java/com/keeper/homepage/domain/library/api/BorrowManageController.kt
  src/main/java/com/keeper/homepage/domain/library/application/BorrowManageService.kt
  src/main/java/com/keeper/homepage/domain/library/entity/Book.java
  src/main/java/com/keeper/homepage/domain/library/entity/BookBorrowInfo.java
  src/main/java/com/keeper/homepage/global/error/ErrorCode.java
  src/test/java/com/keeper/homepage/domain/library/BookTestHelper.java
  src/test/java/com/keeper/homepage/domain/library/api/BorrowManageApiTestHelper.kt
  src/test/java/com/keeper/homepage/domain/library/api/BorrowManageControllerTest.kt
Labels: 🚀 feature, ⭐️ backend

#156 refactor: OCP 준수해보기
  src/main/java/com/keeper/homepage/domain/library/application/BorrowManageService.kt
  src/main/java/com/keeper/homepage/domain/library/dto/req/BorrowStatusDto.kt
Labels: 🛠️ refactor

#158 fix: Datetime 포맷팅 문제 해결
  src/test/java/com/keeper/homepage/domain/library/api/BorrowManageControllerTest.kt
Labels: 🐞 bug, ✅ test
