Repository KEEPER31337/Homepage-Back-R2, pull requests merged in 2023-01, with the labels that each got.

#2 docs: PR Template 생성
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 📄 docs, 🚀 feature

#19 공통 exception 처리 코드 작성
  src/main/java/com/keeper/homepage/global/error/BusinessException.java
  src/main/java/com/keeper/homepage/global/error/ErrorCode.java
  src/main/java/com/keeper/homepage/global/error/ErrorResponse.java
  src/main/java/com/keeper/homepage/global/error/ExceptionAdvice.java
Labels: ⭐️ backend

#21 Feature/#20 통합 테스트 환경 설정
  src/test/java/com/keeper/homepage/HomepageApplicationTests.java
  src/test/java/com/keeper/homepage/IntegrationTest.java
  src/test/resources/org/springframework/restdocs/templates/query-parameters.snippet
  src/test/resources/org/springframework/restdocs/templates/request-fields.snippet
  src/test/resources/org/springframework/restdocs/templates/request-parts.snippet
Labels: 🔥 Emergency, ☑️ test, ⭐️ backend

#22 spring security 설정
  build.gradle
  src/main/java/com/keeper/homepage/domain/auth/api/AuthController.java
  src/main/java/com/keeper/homepage/domain/member/dao/role/MemberJobRepository.java
  src/main/java/com/keeper/homepage/domain/member/entity/Member.java
  src/main/java/com/keeper/homepage/domain/member/entity/job/MemberHasMemberJob.java
  src/main/java/com/keeper/homepage/domain/member/entity/job/MemberJob.java
  src/main/java/com/keeper/homepage/domain/thumbnail/entity/Thumbnail.java
  src/main/java/com/keeper/homepage/global/config/security/JwtTokenProvider.java
  src/main/java/com/keeper/homepage/global/config/security/SecurityConfiguration.java
  src/main/java/com/keeper/homepage/global/config/security/annotation/AuthId.java
  src/main/java/com/keeper/homepage/global/config/security/annotation/AuthIdArgumentResolver.java
  src/main/java/com/keeper/homepage/global/config/security/data/JwtUserDetails.java
  src/main/java/com/keeper/homepage/global/config/security/data/JwtValidationType.java
  src/main/java/com/keeper/homepage/global/config/security/data/TokenValidationResultDto.java
  src/main/java/com/keeper/homepage/global/config/security/exception/EmptyJwtException.java
  src/main/java/com/keeper/homepage/global/config/security/filter/JwtAuthenticationFilter.java
  src/main/java/com/keeper/homepage/global/config/security/handler/CustomAccessDeniedHandler.java
  src/main/java/com/keeper/homepage/global/config/security/handler/CustomAuthenticationEntryPoint.java
  src/main/java/com/keeper/homepage/global/config/web/WebMvcConfiguration.java
  src/main/java/com/keeper/homepage/global/error/ErrorCode.java
  src/test/java/com/keeper/homepage/IntegrationTest.java
  src/test/java/com/keeper/homepage/domain/auth/api/AuthControllerTest.java
  src/test/java/com/keeper/homepage/domain/member/dao/role/MemberJobRepositoryTest.java
  src/test/java/com/keeper/homepage/global/config/security/JwtTokenProviderTest.java
Labels: 🔥 Emergency, ⭐️ backend

#26 Feature/#25 썸네일 유틸리티 제작
  src/main/java/com/keeper/homepage/domain/file/dao/FileRepository.java
  src/main/java/com/keeper/homepage/domain/file/entity/FileEntity.java
  src/main/java/com/keeper/homepage/domain/thumbnail/dao/ThumbnailRepository.java
  src/main/java/com/keeper/homepage/domain/thumbnail/entity/Thumbnail.java
  src/main/java/com/keeper/homepage/global/config/security/SecurityConfiguration.java
  src/main/java/com/keeper/homepage/global/config/web/WebMvcConfiguration.java
  src/main/java/com/keeper/homepage/global/util/file/FileUtil.java
  src/main/java/com/keeper/homepage/global/util/file/exception/FileDeleteFailedException.java
  src/main/java/com/keeper/homepage/global/util/file/exception/FileSaveFailedException.java
  src/main/java/com/keeper/homepage/global/util/file/server/FileServerConstants.java
  src/main/java/com/keeper/homepage/global/util/file/server/FileServerUtil.java
  src/main/java/com/keeper/homepage/global/util/thumbnail/ThumbnailType.java
  src/main/java/com/keeper/homepage/global/util/thumbnail/ThumbnailUtil.java
  src/main/java/com/keeper/homepage/global/util/thumbnail/exception/ThumbnailException.java
  src/main/java/com/keeper/homepage/global/util/thumbnail/server/ThumbnailServerConstants.java
  src/main/java/com/keeper/homepage/global/util/thumbnail/server/ThumbnailServerPathGenerator.java
  src/main/java/com/keeper/homepage/global/util/thumbnail/server/ThumbnailServerUtil.java
  src/main/java/com/keeper/homepage/global/util/thumbnail/server/ThumbnailServerValidator.java
  src/main/java/com/keeper/homepage/global/util/web/WebUtil.java
  src/test/java/com/keeper/homepage/IntegrationTest.java
  src/test/java/com/keeper/homepage/global/util/file/FileServerUtilTest.java
  src/test/java/com/keeper/homepage/global/util/thumbnail/ThumbnailTestHelper.java
  src/test/java/com/keeper/homepage/global/util/thumbnail/server/ThumbnailServerPathGeneratorTest.java
  src/test/java/com/keeper/homepage/global/util/thumbnail/server/ThumbnailServerUtilTest.java
  src/test/java/com/keeper/homepage/global/util/thumbnail/server/ThumbnailServerValidatorTest.java
  src/test/resources/images/fakeImage.png
  src/test/resources/images/testImage_1x1.png
  src/test/resources/images/testImage_210x210.png
Labels: 🚀 feature, ⭐️ backend

#24 Feature/static write 관련 entity repository 생성 #11
  src/main/java/com/keeper/homepage/domain/about/converter/StaticWriteTitleTypeConverter.java
  src/main/java/com/keeper/homepage/domain/about/dao/StaticWriteContentRepository.java
  src/main/java/com/keeper/homepage/domain/about/dao/StaticWriteSubtitleImageRepository.java
  src/main/java/com/keeper/homepage/domain/about/dao/StaticWriteTitleRepository.java
  src/main/java/com/keeper/homepage/domain/about/entity/StaticWriteContent.java
  src/main/java/com/keeper/homepage/domain/about/entity/StaticWriteSubtitleImage.java
  src/main/java/com/keeper/homepage/domain/about/entity/StaticWriteTitle.java
  src/test/java/com/keeper/homepage/IntegrationTest.java
  src/test/java/com/keeper/homepage/domain/about/StaticWriteTestHelper.java
  src/test/java/com/keeper/homepage/domain/about/dao/StaticWriteRepositoryTest.java
Labels: 🚀 feature, ☑️ test, ⭐️ backend

#28 Feature/#27 refresh token 개발
  build.gradle
  src/main/java/com/keeper/homepage/domain/auth/api/test/AuthTestController.java
  src/main/java/com/keeper/homepage/global/config/redis/RedisConfiguration.java
  src/main/java/com/keeper/homepage/global/config/security/JwtTokenProvider.java
  src/main/java/com/keeper/homepage/global/config/security/SecurityConfiguration.java
  src/main/java/com/keeper/homepage/global/config/security/annotation/AuthIdArgumentResolver.java
  src/main/java/com/keeper/homepage/global/config/security/data/JwtType.java
  src/main/java/com/keeper/homepage/global/config/security/filter/JwtAuthenticationFilter.java
  src/main/java/com/keeper/homepage/global/config/security/filter/RefreshTokenFilter.java
  src/main/java/com/keeper/homepage/global/config/web/WebMvcConfiguration.java
  src/main/java/com/keeper/homepage/global/util/redis/RedisUtil.java
  src/test/java/com/keeper/homepage/IntegrationTest.java
  src/test/java/com/keeper/homepage/domain/auth/api/AuthControllerTest.java
  src/test/java/com/keeper/homepage/domain/auth/api/AuthTestControllerTest.java
  src/test/java/com/keeper/homepage/global/config/security/JwtTokenProviderTest.java
Labels: 🚀 feature, ⭐️ backend

#29 #13 attendance entity repository 생성
  src/main/java/com/keeper/homepage/domain/attendance/dao/AttendanceRepository.java
  src/main/java/com/keeper/homepage/domain/attendance/entity/Attendance.java
  src/main/java/com/keeper/homepage/domain/member/dao/MemberRepository.java
  src/main/java/com/keeper/homepage/domain/member/entity/Member.java
  src/test/java/com/keeper/homepage/IntegrationTest.java
  src/test/java/com/keeper/homepage/domain/attendance/AttendanceTestHelper.java
  src/test/java/com/keeper/homepage/domain/attendance/dao/AttendanceRepositoryTest.java
  src/test/java/com/keeper/homepage/domain/member/MemberTestHelper.java
  src/test/java/com/keeper/homepage/domain/member/dao/MemberRepositoryTest.java
Labels: 🚀 feature, ⭐️ backend

#49 Feature/#44 member test helper에 generate() 메서드 추가
  src/test/java/com/keeper/homepage/domain/attendance/AttendanceTestHelper.java
  src/test/java/com/keeper/homepage/domain/attendance/dao/AttendanceRepositoryTest.java
  src/test/java/com/keeper/homepage/domain/member/MemberTestHelper.java
  src/test/java/com/keeper/homepage/domain/member/dao/MemberRepositoryTest.java
Labels: 🚀 feature, ⭐️ backend

#40 Feature/#31 이메일 인증 구현
  build.gradle
  src/docs/auth/auth.adoc
  src/docs/keeper.adoc
  src/main/java/com/keeper/homepage/domain/auth/api/SignUpController.java
  src/main/java/com/keeper/homepage/domain/auth/application/EmailAuthService.java
  src/main/java/com/keeper/homepage/domain/auth/dao/redis/EmailAuthRedisRepository.java
  src/main/java/com/keeper/homepage/domain/auth/dto/request/EmailAuthRequest.java
  src/main/java/com/keeper/homepage/domain/auth/dto/response/EmailAuthResponse.java
  src/main/java/com/keeper/homepage/domain/auth/entity/redis/EmailAuthRedis.java
  src/main/java/com/keeper/homepage/global/config/security/SecurityConfiguration.java
  src/main/java/com/keeper/homepage/global/error/ErrorCode.java
  src/main/java/com/keeper/homepage/global/util/mail/MailUtil.java
  src/test/java/com/keeper/homepage/IntegrationTest.java
  src/test/java/com/keeper/homepage/domain/auth/api/SignUpControllerTest.java
  src/test/java/com/keeper/homepage/domain/auth/api/test/AuthTestControllerTest.java
  src/test/java/com/keeper/homepage/domain/auth/application/EmailAuthServiceTest.java
  src/test/java/com/keeper/homepage/global/util/mail/MailUtilTest.java
Labels: 🚀 feature, ⭐️ backend

#42 feat: Friend Entity, Repository 생성 #38
  src/main/java/com/keeper/homepage/domain/member/dao/friend/FriendRepository.java
  src/main/java/com/keeper/homepage/domain/member/entity/Member.java
  src/main/java/com/keeper/homepage/domain/member/entity/friend/Friend.java
  src/test/java/com/keeper/homepage/IntegrationTest.java
  src/test/java/com/keeper/homepage/domain/member/dao/friend/FriendRepositoryTest.java
Labels: 🚀 feature, ⭐️ backend

#51 Feature/#30 회원가입 구현
  src/docs/auth/auth.adoc
  src/main/java/com/keeper/homepage/domain/auth/api/SignUpController.java
  src/main/java/com/keeper/homepage/domain/auth/application/CheckDuplicateService.java
  src/main/java/com/keeper/homepage/domain/auth/application/SignUpService.java
  src/main/java/com/keeper/homepage/domain/auth/dto/request/SignUpRequest.java
  src/main/java/com/keeper/homepage/domain/member/dao/MemberRepository.java
  src/main/java/com/keeper/homepage/domain/member/entity/Member.java
  src/main/java/com/keeper/homepage/domain/member/entity/embedded/Generation.java
  src/main/java/com/keeper/homepage/domain/member/entity/embedded/Profile.java
  src/main/java/com/keeper/homepage/global/config/password/PasswordConfiguration.java
  src/main/java/com/keeper/homepage/global/config/security/SecurityConfiguration.java
  src/main/java/com/keeper/homepage/global/error/ErrorCode.java
  src/main/java/com/keeper/homepage/global/error/ExceptionAdvice.java
  src/test/java/com/keeper/homepage/IntegrationTest.java
  src/test/java/com/keeper/homepage/domain/auth/api/SignUpControllerTest.java
  src/test/java/com/keeper/homepage/domain/auth/application/CheckDuplicateServiceTest.java
  src/test/java/com/keeper/homepage/domain/auth/application/SignUpServiceTest.java
  src/test/java/com/keeper/homepage/domain/member/MemberTestHelper.java
  src/test/java/com/keeper/homepage/domain/member/dao/MemberRepositoryTest.java
Labels: 🚀 feature, ⭐️ backend
