Repository KEEPER31337/Homepage-Back-R2, pull requests merged in 2023-08, with the labels that each got.

#268 Feature/#267 썸네일 디폴트 이미지 응답 처리
  src/main/java/com/keeper/homepage/domain/game/dto/res/GameRankResponse.kt
  src/main/java/com/keeper/homepage/domain/library/dto/resp/BookDetailResponse.kt
  src/main/java/com/keeper/homepage/domain/library/entity/Book.java
  src/main/java/com/keeper/homepage/domain/member/entity/Member.java
  src/main/java/com/keeper/homepage/domain/post/dao/PostRepository.java
  src/main/java/com/keeper/homepage/domain/post/entity/Post.java
  src/main/java/com/keeper/homepage/domain/study/entity/Study.java
  src/main/java/com/keeper/homepage/domain/thumbnail/entity/Thumbnail.java
  src/test/java/com/keeper/homepage/domain/post/application/PostServiceTest.java
Labels: ⭐️ backend

#264 Feature/Election 관련 entity repository 생성
  src/main/java/com/keeper/homepage/domain/election/dao/ElectionCandidateRepository.java
  src/main/java/com/keeper/homepage/domain/election/dao/ElectionChartLogRepository.java
  src/main/java/com/keeper/homepage/domain/election/dao/ElectionRepository.java
  src/main/java/com/keeper/homepage/domain/election/dao/ElectionVoterRepository.java
  src/main/java/com/keeper/homepage/domain/election/entity/Election.java
  src/main/java/com/keeper/homepage/domain/election/entity/ElectionCandidate.java
  src/main/java/com/keeper/homepage/domain/election/entity/ElectionChartLog.java
  src/main/java/com/keeper/homepage/domain/election/entity/ElectionVoter.java
  src/main/java/com/keeper/homepage/domain/election/entity/ElectionVoterPK.java
  src/test/java/com/keeper/homepage/IntegrationTest.java
  src/test/java/com/keeper/homepage/domain/election/ElectionTestHelper.java
  src/test/java/com/keeper/homepage/domain/election/ElectionVoterTestHelper.java
  src/test/java/com/keeper/homepage/domain/election/dao/ElectionRepositoryTest.java
  src/test/java/com/keeper/homepage/domain/election/dao/ElectionVoterRepositoryTest.java
Labels: 🚀 feature, ⭐️ backend

#259 Feature/익명 게시글 response 처리
  src/main/java/com/keeper/homepage/domain/comment/application/CommentService.java
  src/main/java/com/keeper/homepage/domain/comment/dto/response/CommentResponse.java
  src/main/java/com/keeper/homepage/domain/post/application/PostService.java
  src/main/java/com/keeper/homepage/domain/post/converter/CategoryTypeConverter.java
  src/main/java/com/keeper/homepage/domain/post/dao/PostRepository.java
  src/main/java/com/keeper/homepage/domain/post/dto/response/PostDetailResponse.java
  src/main/java/com/keeper/homepage/domain/post/dto/response/PostResponse.java
  src/main/java/com/keeper/homepage/domain/post/entity/Post.java
  src/main/java/com/keeper/homepage/domain/post/entity/category/Category.java
  src/test/java/com/keeper/homepage/IntegrationTest.java
  src/test/java/com/keeper/homepage/domain/post/CategoryTestHelper.java
  src/test/java/com/keeper/homepage/domain/post/PostTestHelper.java
  src/test/java/com/keeper/homepage/domain/post/api/AdminPostControllerTest.java
  src/test/java/com/keeper/homepage/domain/post/api/PostApiTestHelper.java
  src/test/java/com/keeper/homepage/domain/post/api/PostControllerTest.java
  src/test/java/com/keeper/homepage/domain/post/application/PostServiceTest.java
  src/test/java/com/keeper/homepage/domain/post/dao/PostRepositoryTest.java
Labels: ⭐️ backend, 🐬 DB

#266 Feature/ctf challenge entity 개발
  src/docs/asciidoc/keeper.adoc
  src/main/java/com/keeper/homepage/domain/ctf/converter/CtfChallengeCategoryTypeConverter.java
  src/main/java/com/keeper/homepage/domain/ctf/dao/CtfFlagRepository.java
  src/main/java/com/keeper/homepage/domain/ctf/dao/CtfSubmitLogRepository.java
  src/main/java/com/keeper/homepage/domain/ctf/dao/challenge/CtfChallengeCategoryRepository.java
  src/main/java/com/keeper/homepage/domain/ctf/dao/challenge/CtfChallengeHasCtfChallengeCategoryRepository.java
  src/main/java/com/keeper/homepage/domain/ctf/dao/challenge/CtfChallengeHasFileRepository.java
  src/main/java/com/keeper/homepage/domain/ctf/dao/challenge/CtfChallengeRepository.java
  src/main/java/com/keeper/homepage/domain/ctf/dao/challenge/CtfChallengeTypeRepository.java
  src/main/java/com/keeper/homepage/domain/ctf/dao/challenge/CtfDynamicChallengeInfoRepository.java
  src/main/java/com/keeper/homepage/domain/ctf/entity/CtfFlag.java
  src/main/java/com/keeper/homepage/domain/ctf/entity/CtfSubmitLog.java
  src/main/java/com/keeper/homepage/domain/ctf/entity/challenge/CtfChallenge.java
  src/main/java/com/keeper/homepage/domain/ctf/entity/challenge/CtfChallengeCategory.java
  src/main/java/com/keeper/homepage/domain/ctf/entity/challenge/CtfChallengeHasCtfChallengeCategory.java
  src/main/java/com/keeper/homepage/domain/ctf/entity/challenge/CtfChallengeHasFile.java
  src/main/java/com/keeper/homepage/domain/ctf/entity/challenge/CtfChallengeHasFilePK.java
  src/main/java/com/keeper/homepage/domain/ctf/entity/challenge/CtfChallengeType.java
  src/main/java/com/keeper/homepage/domain/ctf/entity/challenge/CtfDynamicChallengeInfo.java
  src/test/java/com/keeper/homepage/IntegrationTest.java
  src/test/java/com/keeper/homepage/domain/ctf/CtfChallengeTestHelper.java
  src/test/java/com/keeper/homepage/domain/ctf/CtfFlagTestHelper.java
  src/test/java/com/keeper/homepage/domain/ctf/dao/CtfChallengeCategoryRepositoryTest.java
  src/test/java/com/keeper/homepage/domain/ctf/dao/CtfChallengeRepositoryTest.java
  src/test/java/com/keeper/homepage/domain/ctf/dao/CtfChallengeTypeRepositoryTest.java
Labels: 🚀 feature, ⭐️ backend

#271 Feature/첨부파일 목록 조회 api 분리
  src/docs/asciidoc/keeper.adoc
  src/docs/asciidoc/post/admin-post.adoc
  src/docs/asciidoc/post/post.adoc
  src/main/java/com/keeper/homepage/domain/comment/api/CommentController.java
  src/main/java/com/keeper/homepage/domain/comment/application/CommentService.java
  src/main/java/com/keeper/homepage/domain/comment/dto/response/CommentResponse.java
  src/main/java/com/keeper/homepage/domain/member/entity/Member.java
  src/main/java/com/keeper/homepage/domain/member/entity/post/MemberReadPost.java
  src/main/java/com/keeper/homepage/domain/post/api/PostController.java
  src/main/java/com/keeper/homepage/domain/post/application/PostService.java
  src/main/java/com/keeper/homepage/domain/post/dto/response/PostDetailResponse.java
  src/main/java/com/keeper/homepage/domain/post/entity/Post.java
  src/test/java/com/keeper/homepage/domain/comment/api/CommentControllerTest.java
  src/test/java/com/keeper/homepage/domain/comment/application/CommentServiceTest.java
  src/test/java/com/keeper/homepage/domain/post/api/PostControllerTest.java
  src/test/java/com/keeper/homepage/domain/post/application/PostServiceTest.java
Labels: 🚀 feature, ⭐️ backend

#278 Feature/ctf 대회 api 구현
  src/docs/asciidoc/ctf/ctf-contest.adoc
  src/docs/asciidoc/keeper.adoc
  src/main/java/com/keeper/homepage/domain/ctf/api/CtfContestController.java
  src/main/java/com/keeper/homepage/domain/ctf/api/CtfTeamController.java
  src/main/java/com/keeper/homepage/domain/ctf/application/CtfContestService.java
  src/main/java/com/keeper/homepage/domain/ctf/application/CtfTeamService.java
  src/main/java/com/keeper/homepage/domain/ctf/application/convenience/CtfContestFindService.java
  src/main/java/com/keeper/homepage/domain/ctf/dao/CtfContestRepository.java
  src/main/java/com/keeper/homepage/domain/ctf/dto/request/contest/CreateContestRequest.java
  src/main/java/com/keeper/homepage/domain/ctf/dto/request/contest/UpdateContestRequest.java
  src/main/java/com/keeper/homepage/domain/ctf/dto/request/team/CreateTeamRequest.java
  src/main/java/com/keeper/homepage/domain/ctf/dto/request/team/JoinTeamRequest.java
  src/main/java/com/keeper/homepage/domain/ctf/dto/request/team/UpdateTeamRequest.java
  src/main/java/com/keeper/homepage/domain/ctf/dto/response/CtfChallengeResponse.java
  src/main/java/com/keeper/homepage/domain/ctf/dto/response/challenge/CtfChallengeResponse.java
  src/main/java/com/keeper/homepage/domain/ctf/dto/response/contest/CtfContestResponse.java
  src/main/java/com/keeper/homepage/domain/ctf/dto/response/team/CtfTeamDetailResponse.java
  src/main/java/com/keeper/homepage/domain/ctf/dto/response/team/CtfTeamResponse.java
  src/main/java/com/keeper/homepage/domain/ctf/entity/CtfContest.java
  src/test/java/com/keeper/homepage/domain/ctf/api/CtfContestControllerTest.java
  src/test/java/com/keeper/homepage/domain/ctf/api/CtfTeamControllerTest.java
Labels: 🚀 feature, ⭐️ backend

#277 Feature/도서 반납 요청 기능 구현
  src/docs/asciidoc/library/book.adoc
  src/main/java/com/keeper/homepage/domain/library/api/BookController.java
  src/main/java/com/keeper/homepage/domain/library/application/BookService.java
  src/main/java/com/keeper/homepage/domain/library/entity/BookBorrowInfo.java
  src/main/java/com/keeper/homepage/domain/member/entity/Member.java
  src/main/java/com/keeper/homepage/global/error/ErrorCode.java
  src/test/java/com/keeper/homepage/domain/library/api/BookApiTestHelper.java
  src/test/java/com/keeper/homepage/domain/library/api/BookControllerTest.java
  src/test/java/com/keeper/homepage/domain/library/application/BookServiceTest.java
Labels: ⭐️ backend

#273 feat: 상벌점 엔티티 & 레포지토리 구현
  src/docs/asciidoc/merit/merit.adoc
  src/main/java/com/keeper/homepage/domain/member/entity/Member.java
  src/main/java/com/keeper/homepage/domain/member/entity/embedded/MeritDemerit.java
  src/main/java/com/keeper/homepage/domain/merit/api/MeritController.java
  src/main/java/com/keeper/homepage/domain/merit/application/MeritLogService.java
  src/main/java/com/keeper/homepage/domain/merit/application/MeritTypeService.java
  src/main/java/com/keeper/homepage/domain/merit/dao/MeritLogRepository.java
  src/main/java/com/keeper/homepage/domain/merit/dao/MeritTypeRepository.java
  src/main/java/com/keeper/homepage/domain/merit/dto/request/AddMeritTypeRequest.java
  src/main/java/com/keeper/homepage/domain/merit/dto/request/GiveMeritPointRequest.java
  src/main/java/com/keeper/homepage/domain/merit/dto/request/UpdateMeritTypeRequest.java
  src/main/java/com/keeper/homepage/domain/merit/dto/response/MeritTypeResponse.java
  src/main/java/com/keeper/homepage/domain/merit/dto/response/SearchMemberMeritLogResponse.java
  src/main/java/com/keeper/homepage/domain/merit/dto/response/SearchMeritLogListResponse.java
  src/main/java/com/keeper/homepage/domain/merit/entity/MeritLog.java
  src/main/java/com/keeper/homepage/domain/merit/entity/MeritType.java
  src/main/java/com/keeper/homepage/global/error/ErrorCode.java
  src/test/java/com/keeper/homepage/IntegrationTest.java
  src/test/java/com/keeper/homepage/domain/merit/MeritLogTestHelper.java
  src/test/java/com/keeper/homepage/domain/merit/MeritTypeHelper.java
  src/test/java/com/keeper/homepage/domain/merit/api/MeritApiTestHelper.java
  src/test/java/com/keeper/homepage/domain/merit/api/MeritControllerTest.java
  src/test/java/com/keeper/homepage/domain/merit/application/MeritLogServiceTest.java
  src/test/java/com/keeper/homepage/domain/merit/application/MeritTypeServiceTest.java
  src/test/java/com/keeper/homepage/domain/merit/dao/MeritLogRepositoryTest.java
  src/test/java/com/keeper/homepage/domain/merit/dao/MeritTypeRepositoryTest.java
Labels: 🚀 feature, ⭐️ backend

#289 Feature/선거 생성 기능 구현
  src/docs/asciidoc/election/election-manage.adoc
  src/main/java/com/keeper/homepage/domain/election/api/AdminElectionController.java
  src/main/java/com/keeper/homepage/domain/election/application/AdminElectionService.java
  src/main/java/com/keeper/homepage/domain/election/dto/request/ElectionCreateRequest.java
  src/test/java/com/keeper/homepage/IntegrationTest.java
  src/test/java/com/keeper/homepage/domain/election/api/AdminElectionApiTestHelper.java
  src/test/java/com/keeper/homepage/domain/election/api/AdminTestElectionControllerTest.java
  src/test/java/com/keeper/homepage/domain/election/application/AdminElectionServiceTest.java
Labels: 🚀 feature

#287 Feature/출석부 기능 구현
  src/docs/asciidoc/attendance/attendance.adoc
  src/main/java/com/keeper/homepage/domain/attendance/api/AttendanceController.java
  src/main/java/com/keeper/homepage/domain/attendance/application/AttendanceService.java
  src/main/java/com/keeper/homepage/domain/attendance/dao/AttendanceRepository.java
  src/main/java/com/keeper/homepage/domain/attendance/dto/response/AttendanceInfoResponse.java
  src/main/java/com/keeper/homepage/domain/attendance/dto/response/AttendancePointResponse.java
  src/main/java/com/keeper/homepage/domain/attendance/dto/response/AttendanceRankResponse.java
  src/main/java/com/keeper/homepage/domain/attendance/dto/response/AttendanceResponse.java
  src/main/java/com/keeper/homepage/global/error/ErrorCode.java
  src/test/java/com/keeper/homepage/domain/attendance/api/AttendanceControllerTest.java
Labels: 🚀 feature, ⭐️ backend

#286 feat: 족보 열람시 차감된 포인트 로그 생성 코드 추가
  src/main/java/com/keeper/homepage/domain/attendance/application/AttendanceService.java
  src/main/java/com/keeper/homepage/domain/game/application/BaseballService.kt
  src/main/java/com/keeper/homepage/domain/member/entity/Member.java
  src/main/java/com/keeper/homepage/domain/point/application/PointLogService.java
  src/main/java/com/keeper/homepage/domain/point/entity/PointLog.java
  src/main/java/com/keeper/homepage/domain/post/application/PostService.java
  src/test/java/com/keeper/homepage/domain/game/api/GameControllerTest.kt
Labels: ⭐️ backend

#296 Feature/선거 삭제 기능 구현
  src/docs/asciidoc/election/election-manage.adoc
  src/docs/asciidoc/keeper.adoc
  src/main/java/com/keeper/homepage/domain/election/api/AdminElectionController.java
  src/main/java/com/keeper/homepage/domain/election/application/AdminElectionService.java
  src/main/java/com/keeper/homepage/domain/election/application/convenience/ElectionDeleteService.java
  src/main/java/com/keeper/homepage/domain/election/application/convenience/ValidElectionFindService.java
  src/main/java/com/keeper/homepage/domain/election/dao/ElectionRepository.java
  src/main/java/com/keeper/homepage/domain/election/dao/ElectionVoterRepository.java
  src/main/java/com/keeper/homepage/domain/election/entity/Election.java
  src/main/java/com/keeper/homepage/global/error/ErrorCode.java
  src/test/java/com/keeper/homepage/domain/election/api/AdminElectionApiTestHelper.java
  src/test/java/com/keeper/homepage/domain/election/api/AdminTestElectionControllerTest.java
  src/test/java/com/keeper/homepage/domain/election/application/AdminElectionServiceTest.java
Labels: 🚀 feature, ⭐️ backend

#297 Feature/회원의 닉네임 & 상벌점 컬럼 제거 반영
  src/main/java/com/keeper/homepage/domain/attendance/dto/response/AttendanceRankResponse.java
  src/main/java/com/keeper/homepage/domain/auth/dto/request/SignUpRequest.java
  src/main/java/com/keeper/homepage/domain/auth/dto/response/SignInResponse.java
  src/main/java/com/keeper/homepage/domain/comment/application/CommentService.java
  src/main/java/com/keeper/homepage/domain/comment/dto/response/CommentResponse.java
  src/main/java/com/keeper/homepage/domain/game/dto/res/GameRankResponse.kt
  src/main/java/com/keeper/homepage/domain/library/dao/BookBorrowInfoRepository.java
  src/main/java/com/keeper/homepage/domain/library/dto/resp/BorrowDetailResponse.kt
  src/main/java/com/keeper/homepage/domain/member/dto/response/MemberJobResponse.java
  src/main/java/com/keeper/homepage/domain/member/dto/response/MemberPointRankResponse.java
  src/main/java/com/keeper/homepage/domain/member/dto/response/MemberResponse.java
  src/main/java/com/keeper/homepage/domain/member/entity/Member.java
  src/main/java/com/keeper/homepage/domain/member/entity/embedded/MeritDemerit.java
  src/main/java/com/keeper/homepage/domain/member/entity/embedded/Nickname.java
  src/main/java/com/keeper/homepage/domain/member/entity/embedded/Profile.java
  src/main/java/com/keeper/homepage/domain/merit/api/MeritController.java
  src/main/java/com/keeper/homepage/domain/merit/application/MeritLogService.java
  src/main/java/com/keeper/homepage/domain/merit/application/MeritTypeService.java
  src/main/java/com/keeper/homepage/domain/merit/dao/MeritLogRepository.java
  src/main/java/com/keeper/homepage/domain/merit/dto/response/SearchMeritLogListResponse.java
  src/main/java/com/keeper/homepage/domain/merit/entity/MeritLog.java
  src/main/java/com/keeper/homepage/domain/merit/entity/MeritType.java
  src/main/java/com/keeper/homepage/domain/post/dao/PostRepository.java
  src/main/java/com/keeper/homepage/domain/post/dto/response/PostDetailResponse.java
  src/main/java/com/keeper/homepage/domain/post/dto/response/PostResponse.java
  src/main/java/com/keeper/homepage/domain/post/entity/Post.java
  src/main/java/com/keeper/homepage/domain/seminar/application/SeminarAttendanceService.java
  src/test/java/com/keeper/homepage/domain/attendance/api/AttendanceControllerTest.java
  src/test/java/com/keeper/homepage/domain/auth/api/SignInControllerTest.java
  src/test/java/com/keeper/homepage/domain/auth/api/SignUpControllerTest.java
  src/test/java/com/keeper/homepage/domain/auth/application/SignUpServiceTest.java
  src/test/java/com/keeper/homepage/domain/comment/application/CommentServiceTest.java
  src/test/java/com/keeper/homepage/domain/game/api/GameControllerTest.kt
  src/test/java/com/keeper/homepage/domain/library/api/BookManageApiTestHelper.kt
  src/test/java/com/keeper/homepage/domain/library/api/BookManageControllerTest.kt
  src/test/java/com/keeper/homepage/domain/library/api/BorrowManageControllerTest.kt
  src/test/java/com/keeper/homepage/domain/member/MemberTestHelper.java
  src/test/java/com/keeper/homepage/domain/member/api/MemberApiTestHelper.java
  src/test/java/com/keeper/homepage/domain/member/dao/MemberRepositoryTest.java
  src/test/java/com/keeper/homepage/domain/merit/MeritLogTestHelper.java
  src/test/java/com/keeper/homepage/domain/merit/MeritTypeHelper.java
  src/test/java/com/keeper/homepage/domain/merit/api/MeritControllerTest.java
  src/test/java/com/keeper/homepage/domain/merit/application/MeritLogServiceTest.java
  src/test/java/com/keeper/homepage/domain/merit/application/MeritTypeServiceTest.java
  src/test/java/com/keeper/homepage/domain/merit/dao/MeritLogRepositoryTest.java
  src/test/java/com/keeper/homepage/domain/merit/dao/MeritTypeRepositoryTest.java
  src/test/java/com/keeper/homepage/domain/post/api/PostApiTestHelper.java
  src/test/java/com/keeper/homepage/domain/post/api/PostControllerTest.java
  src/test/java/com/keeper/homepage/domain/post/application/PostServiceTest.java
Labels: 👋 FE needs, 🚀 feature, ⭐️ backend, 🐬 DB

#294 Feature/회원 팔로우 & 팔로우 취소 구현
  src/docs/asciidoc/member/member.adoc
  src/main/java/com/keeper/homepage/domain/member/api/MemberController.java
  src/main/java/com/keeper/homepage/domain/member/application/MemberService.java
  src/main/java/com/keeper/homepage/domain/member/entity/Member.java
  src/main/java/com/keeper/homepage/global/error/ErrorCode.java
  src/test/java/com/keeper/homepage/domain/member/api/MemberControllerTest.java
  src/test/java/com/keeper/homepage/domain/member/application/MemberServiceTest.java
Labels: 🚀 feature, ⭐️ backend

#288 Feature/inner enum의 from code 메서드가 던지는 exception 수정
  src/main/java/com/keeper/homepage/domain/about/converter/StaticWriteTitleTypeConverter.java
  src/main/java/com/keeper/homepage/domain/about/entity/StaticWriteTitle.java
  src/main/java/com/keeper/homepage/domain/library/entity/BookBorrowStatus.java
  src/main/java/com/keeper/homepage/domain/library/entity/BookDepartment.java
  src/main/java/com/keeper/homepage/domain/seminar/entity/SeminarAttendanceStatus.java
  src/main/java/com/keeper/homepage/domain/survey/entity/SurveyReply.java
  src/main/java/com/keeper/homepage/global/error/ErrorCode.java
Labels: 🛠️ refactor, 👀 good first issue

#292 Feature/포인트 기능 구현
  src/docs/asciidoc/keeper.adoc
  src/docs/asciidoc/point/point.adoc
  src/main/java/com/keeper/homepage/domain/point/api/PointController.java
  src/main/java/com/keeper/homepage/domain/point/application/GivePointService.java
  src/main/java/com/keeper/homepage/domain/point/application/PointLogService.java
  src/main/java/com/keeper/homepage/domain/point/dao/PointLogRepository.java
  src/main/java/com/keeper/homepage/domain/point/dto/request/presentPointRequest.java
  src/main/java/com/keeper/homepage/domain/point/dto/response/FindAllPointLogResponse.java
  src/test/java/com/keeper/homepage/IntegrationTest.java
  src/test/java/com/keeper/homepage/domain/point/PointLogTestHelper.java
  src/test/java/com/keeper/homepage/domain/point/api/PointControllerTest.java
  src/test/java/com/keeper/homepage/domain/point/application/GivePointServiceTest.java
  src/test/java/com/keeper/homepage/domain/point/application/PointLogServiceTest.java
Labels: 🚀 feature, ⭐️ backend

#308 Feature/파일 다운로드 기능 구현
  src/docs/asciidoc/keeper.adoc
  src/docs/asciidoc/post/post.adoc
  src/main/java/com/keeper/homepage/domain/file/application/FileService.java
  src/main/java/com/keeper/homepage/domain/file/entity/FileEntity.java
  src/main/java/com/keeper/homepage/domain/member/entity/Member.java
  src/main/java/com/keeper/homepage/domain/post/api/PostController.java
  src/main/java/com/keeper/homepage/domain/post/application/PostService.java
  src/main/java/com/keeper/homepage/domain/post/dao/PostRepository.java
  src/main/java/com/keeper/homepage/domain/post/dto/response/PostResponse.java
  src/main/java/com/keeper/homepage/global/error/ErrorCode.java
  src/test/java/com/keeper/homepage/domain/post/api/PostApiTestHelper.java
  src/test/java/com/keeper/homepage/domain/post/api/PostControllerTest.java
  src/test/java/com/keeper/homepage/domain/post/application/PostServiceTest.java
Labels: 🚀 feature, ⭐️ backend

#309 야구게임 추가 사항
  src/docs/asciidoc/game/baseball.adoc
  src/main/java/com/keeper/homepage/domain/game/api/GameController.kt
  src/main/java/com/keeper/homepage/domain/game/application/BaseballService.kt
  src/main/java/com/keeper/homepage/domain/game/dto/res/BaseballStatusResponse.kt
  src/main/java/com/keeper/homepage/domain/game/dto/res/GameInfoByMemberResponse.kt
  src/main/java/com/keeper/homepage/domain/game/entity/embedded/Baseball.java
  src/main/java/com/keeper/homepage/domain/game/entity/redis/BaseballResultEntity.kt
  src/test/java/com/keeper/homepage/domain/game/api/GameApiTestHelper.kt
  src/test/java/com/keeper/homepage/domain/game/api/GameControllerTest.kt
Labels: ⭐️ backend

#310 Feature/프로필 썸네일 수정
  src/docs/asciidoc/member/member.adoc
  src/main/java/com/keeper/homepage/domain/member/api/MemberController.java
  src/main/java/com/keeper/homepage/domain/member/application/MemberProfileService.java
  src/main/java/com/keeper/homepage/domain/member/entity/embedded/Profile.java
  src/test/java/com/keeper/homepage/IntegrationTest.java
  src/test/java/com/keeper/homepage/domain/member/api/MemberControllerTest.java
  src/test/java/com/keeper/homepage/domain/member/application/MemberProfileServiceTest.java
Labels: 🚀 feature, ⭐️ backend

#302 feat: 회원 프로필 조회 기능 구현 및 테스트 코드 작성
  src/docs/asciidoc/member/member.adoc
  src/main/java/com/keeper/homepage/domain/member/api/MemberController.java
  src/main/java/com/keeper/homepage/domain/member/application/MemberService.java
  src/main/java/com/keeper/homepage/domain/member/dao/friend/FriendRepository.java
  src/main/java/com/keeper/homepage/domain/member/dto/response/profile/MemberFriendResponse.java
  src/main/java/com/keeper/homepage/domain/member/dto/response/profile/MemberProfileResponse.java
  src/main/java/com/keeper/homepage/domain/member/entity/Member.java
  src/test/java/com/keeper/homepage/domain/member/api/MemberApiTestHelper.java
  src/test/java/com/keeper/homepage/domain/member/api/MemberControllerTest.java
Labels: 🚀 feature, ⭐️ backend

#307 Feature/세미나 지각 & 결석 벌점 처리 구현
  src/docs/asciidoc/keeper.adoc
  src/docs/asciidoc/seminar/seminar-attendance.adoc
  src/docs/asciidoc/seminar/seminar.adoc
  src/main/java/com/keeper/homepage/domain/member/entity/Member.java
  src/main/java/com/keeper/homepage/domain/merit/application/MeritLogService.java
  src/main/java/com/keeper/homepage/domain/merit/dao/MeritLogRepository.java
  src/main/java/com/keeper/homepage/domain/seminar/api/SeminarAttendanceController.java
  src/main/java/com/keeper/homepage/domain/seminar/api/SeminarController.java
  src/main/java/com/keeper/homepage/domain/seminar/application/SeminarAttendanceService.java
  src/main/java/com/keeper/homepage/domain/seminar/application/SeminarService.java
  src/main/java/com/keeper/homepage/domain/seminar/dao/SeminarAttendanceRepository.java
  src/main/java/com/keeper/homepage/domain/seminar/entity/SeminarAttendance.java
  src/test/java/com/keeper/homepage/domain/seminar/application/SeminarAttendanceServiceTest.java
Labels: 🚀 feature, ⭐️ backend, 🐬 DB

#311 Feature/스터디 추가 수정사항
  src/docs/asciidoc/study/study.adoc
  src/main/java/com/keeper/homepage/domain/post/entity/category/Category.java
  src/main/java/com/keeper/homepage/domain/study/api/StudyController.java
  src/main/java/com/keeper/homepage/domain/study/application/StudyService.java
  src/main/java/com/keeper/homepage/domain/study/application/convenience/StudyDeleteService.java
  src/main/java/com/keeper/homepage/domain/study/dao/StudyHasMemberRepository.java
  src/main/java/com/keeper/homepage/domain/study/dto/request/StudyCreateRequest.java
  src/main/java/com/keeper/homepage/domain/study/dto/request/StudyJoinRequest.java
  src/main/java/com/keeper/homepage/domain/study/dto/request/StudyUpdateRequest.java
  src/main/java/com/keeper/homepage/domain/study/dto/response/LinkResponse.java
  src/main/java/com/keeper/homepage/domain/study/dto/response/StudyDetailResponse.java
  src/main/java/com/keeper/homepage/domain/study/entity/Study.java
  src/main/java/com/keeper/homepage/domain/study/entity/embedded/GitLink.java
  src/main/java/com/keeper/homepage/domain/study/entity/embedded/Link.java
  src/main/java/com/keeper/homepage/domain/study/entity/embedded/NotionLink.java
  src/test/java/com/keeper/homepage/domain/study/api/StudyControllerTest.java
  src/test/java/com/keeper/homepage/domain/study/application/StudyServiceTest.java
Labels: 🚀 feature, ⭐️ backend, 🐬 DB

#320 Feature/게시글 + 댓글 수정사항
  src/docs/asciidoc/comment/comment.adoc
  src/docs/asciidoc/keeper.adoc
  src/main/java/com/keeper/homepage/domain/attendance/application/AttendanceService.java
  src/main/java/com/keeper/homepage/domain/comment/api/CommentController.java
  src/main/java/com/keeper/homepage/domain/comment/application/CommentService.java
  src/main/java/com/keeper/homepage/domain/comment/dto/request/CommentUpdateRequest.java
  src/main/java/com/keeper/homepage/domain/comment/dto/response/CommentResponse.java
  src/main/java/com/keeper/homepage/domain/comment/entity/Comment.java
  src/main/java/com/keeper/homepage/domain/game/application/BaseballService.kt
  src/main/java/com/keeper/homepage/domain/post/api/PostController.java
  src/main/java/com/keeper/homepage/domain/post/application/PostService.java
  src/main/java/com/keeper/homepage/domain/post/dto/response/CategoryResponse.java
  src/main/java/com/keeper/homepage/domain/post/entity/Post.java
  src/main/java/com/keeper/homepage/global/util/redis/RedisUtil.java
  src/test/java/com/keeper/homepage/domain/comment/api/CommentApiTestHelper.java
  src/test/java/com/keeper/homepage/domain/comment/api/CommentControllerTest.java
  src/test/java/com/keeper/homepage/domain/comment/application/CommentServiceTest.java
  src/test/java/com/keeper/homepage/domain/post/api/PostControllerTest.java
  src/test/java/com/keeper/homepage/domain/post/application/PostServiceTest.java
Labels: ⭐️ backend, 🐬 DB

#316 Feature/선거 후보자 등록 및 삭제 기능 구현
  src/docs/asciidoc/election/election-manage.adoc
  src/main/java/com/keeper/homepage/domain/election/api/AdminElectionController.java
  src/main/java/com/keeper/homepage/domain/election/application/AdminElectionService.java
  src/main/java/com/keeper/homepage/domain/election/application/convenience/ValidCandidateService.java
  src/main/java/com/keeper/homepage/domain/election/application/convenience/ValidElectionFindService.java
  src/main/java/com/keeper/homepage/domain/election/dao/ElectionCandidateRepository.java
  src/main/java/com/keeper/homepage/domain/election/dao/ElectionRepository.java
  src/main/java/com/keeper/homepage/domain/election/dto/request/ElectionCandidateRegisterRequest.java
  src/main/java/com/keeper/homepage/domain/election/dto/request/ElectionCandidatesRegisterRequest.java
  src/main/java/com/keeper/homepage/domain/election/entity/ElectionCandidate.java
  src/main/java/com/keeper/homepage/global/error/ErrorCode.java
  src/test/java/com/keeper/homepage/IntegrationTest.java
  src/test/java/com/keeper/homepage/domain/election/ElectionCandidateTestHelper.java
  src/test/java/com/keeper/homepage/domain/election/ElectionTestHelper.java
  src/test/java/com/keeper/homepage/domain/election/ElectionVoterTestHelper.java
  src/test/java/com/keeper/homepage/domain/election/api/AdminElectionApiTestHelper.java
  src/test/java/com/keeper/homepage/domain/election/api/AdminTestElectionControllerTest.java
  src/test/java/com/keeper/homepage/domain/election/application/AdminElectionServiceTest.java
Labels: 🚀 feature, ⭐️ backend

#324 fix: refreshToken redis 저장 시 Id + userAgent 사용
  src/main/java/com/keeper/homepage/domain/auth/api/SignInController.java
  src/main/java/com/keeper/homepage/domain/auth/application/AuthCookieService.java
  src/main/java/com/keeper/homepage/domain/auth/application/SignInService.java
  src/main/java/com/keeper/homepage/global/config/security/JwtTokenProvider.java
  src/main/java/com/keeper/homepage/global/config/security/filter/RefreshTokenFilter.java
  src/test/java/com/keeper/homepage/domain/auth/api/SignInControllerTest.java
  src/test/java/com/keeper/homepage/domain/auth/api/test/AuthTestControllerTest.java
Labels: ⭐️ backend

#321 Feature/회원 타입 변경 기능
  src/docs/asciidoc/member/member.adoc
  src/main/java/com/keeper/homepage/domain/member/api/MemberController.java
  src/main/java/com/keeper/homepage/domain/member/application/MemberService.java
  src/main/java/com/keeper/homepage/domain/member/dto/request/UpdateMemberTypeRequest.java
  src/main/java/com/keeper/homepage/domain/member/entity/Member.java
  src/main/java/com/keeper/homepage/domain/member/entity/type/MemberType.java
  src/main/java/com/keeper/homepage/global/error/ErrorCode.java
  src/test/java/com/keeper/homepage/domain/member/api/MemberControllerTest.java
  src/test/java/com/keeper/homepage/domain/member/application/MemberServiceTest.java
Labels: 🚀 feature, ⭐️ backend

#329 Feature/스터디 변경 요구사항
  src/docs/asciidoc/study/study.adoc
  src/main/java/com/keeper/homepage/domain/member/entity/Member.java
  src/main/java/com/keeper/homepage/domain/study/api/StudyController.java
  src/main/java/com/keeper/homepage/domain/study/application/StudyService.java
  src/main/java/com/keeper/homepage/domain/study/dao/StudyHasMemberRepository.java
  src/main/java/com/keeper/homepage/domain/study/dto/request/StudyCreateRequest.java
  src/main/java/com/keeper/homepage/domain/study/dto/request/StudyUpdateRequest.java
  src/main/java/com/keeper/homepage/domain/study/entity/Study.java
  src/test/java/com/keeper/homepage/domain/study/api/StudyControllerTest.java
  src/test/java/com/keeper/homepage/domain/study/application/StudyServiceTest.java
  src/test/java/com/keeper/homepage/domain/study/dao/StudyHasMemberRepositoryTest.java
Labels: ⭐️ backend

#332 도서 수정사항 반영
  src/main/java/com/keeper/homepage/domain/library/api/BookController.java
  src/main/java/com/keeper/homepage/domain/library/api/BookManageController.kt
  src/main/java/com/keeper/homepage/domain/library/application/BookManageService.kt
  src/main/java/com/keeper/homepage/domain/library/application/BookService.java
  src/main/java/com/keeper/homepage/domain/library/converter/BookSearchTypeConverter.kt
  src/main/java/com/keeper/homepage/domain/library/dao/BookRepository.java
  src/main/java/com/keeper/homepage/domain/library/dto/req/BookSearchType.kt
  src/main/java/com/keeper/homepage/domain/library/dto/resp/BookBorrowResponse.java
  src/main/java/com/keeper/homepage/domain/library/dto/resp/BookDetailResponse.kt
  src/test/java/com/keeper/homepage/domain/library/api/BookApiTestHelper.java
  src/test/java/com/keeper/homepage/domain/library/api/BookManageApiTestHelper.kt
  src/test/java/com/keeper/homepage/domain/library/api/BookManageControllerTest.kt
  src/test/java/com/keeper/homepage/domain/library/application/BookServiceTest.java
Labels: ⭐️ backend

#331 Feature/선거 투표권자 등록과 삭제 및 선거 공개와 비공개 기능 구현
  src/docs/asciidoc/election/election-manage.adoc
  src/main/java/com/keeper/homepage/domain/election/api/AdminElectionController.java
  src/main/java/com/keeper/homepage/domain/election/application/AdminElectionService.java
  src/main/java/com/keeper/homepage/domain/election/application/convenience/ValidVoterService.java
  src/main/java/com/keeper/homepage/domain/election/dao/ElectionVoterRepository.java
  src/main/java/com/keeper/homepage/domain/election/dto/request/ElectionVotersRequest.java
  src/main/java/com/keeper/homepage/domain/election/entity/Election.java
  src/main/java/com/keeper/homepage/global/error/ErrorCode.java
  src/test/java/com/keeper/homepage/domain/election/api/AdminElectionApiTestHelper.java
  src/test/java/com/keeper/homepage/domain/election/api/AdminTestElectionControllerTest.java
  src/test/java/com/keeper/homepage/domain/election/application/AdminElectionServiceTest.java
Labels: 🚀 feature, ⭐️ backend

#334 fix: 게시글 제목 + 내용 검색 시 카테고리 상관없이 검색하던 문제 수정
  src/main/java/com/keeper/homepage/domain/post/dao/PostRepository.java
Labels: 🐞 bug, ⭐️ backend

#333 refactor: String.format에서 formatted로 변경하기 #118
  src/main/java/com/keeper/homepage/global/config/p6spy/PrettySqlFormat.java
  src/main/java/com/keeper/homepage/global/config/password/PasswordFactory.java
  src/main/java/com/keeper/homepage/global/error/ExceptionAdvice.java
  src/test/java/com/keeper/homepage/domain/auth/application/EmailAddressAuthServiceTest.java
Labels: 👀 good first issue

#342 fix: registerTime 응답 형식 "yyyy-mm-dd"로 변경
  src/main/java/com/keeper/homepage/domain/post/dto/response/MainPostResponse.java
  src/main/java/com/keeper/homepage/domain/post/dto/response/MemberPostResponse.java
  src/main/java/com/keeper/homepage/domain/post/dto/response/PostDetailResponse.java
  src/main/java/com/keeper/homepage/domain/post/dto/response/PostResponse.java
  src/main/java/com/keeper/homepage/domain/post/dto/response/TempPostResponse.java
Labels: ⭐️ backend

#317 Feature/프로필 수정 기능 제작
  src/docs/asciidoc/member/member.adoc
  src/main/java/com/keeper/homepage/domain/member/api/MemberController.java
  src/main/java/com/keeper/homepage/domain/member/application/MemberProfileService.java
  src/main/java/com/keeper/homepage/domain/member/dto/request/ProfileUpdateRequest.java
  src/main/java/com/keeper/homepage/domain/member/entity/embedded/Profile.java
  src/test/java/com/keeper/homepage/domain/member/api/MemberApiTestHelper.java
  src/test/java/com/keeper/homepage/domain/member/api/MemberControllerTest.java
Labels: 🚀 feature, ⭐️ backend
