Repository KEEPER31337/Homepage-Back-R2, pull requests merged in 2024-05, with the labels that each got.

#425 Feature/post 엔티티의 필드를 embedded로 교체
  src/main/java/com/keeper/homepage/domain/member/application/convenience/MemberDeleteService.java
  src/main/java/com/keeper/homepage/domain/post/api/PostController.java
  src/main/java/com/keeper/homepage/domain/post/application/PostContentService.java
  src/main/java/com/keeper/homepage/domain/post/application/PostService.java
  src/main/java/com/keeper/homepage/domain/post/dao/PostRepository.java
  src/main/java/com/keeper/homepage/domain/post/dto/request/PostCreateRequest.java
  src/main/java/com/keeper/homepage/domain/post/dto/request/PostUpdateRequest.java
  src/main/java/com/keeper/homepage/domain/post/dto/response/AdjacentPostResponse.java
  src/main/java/com/keeper/homepage/domain/post/dto/response/MainPostResponse.java
  src/main/java/com/keeper/homepage/domain/post/dto/response/MemberPostResponse.java
  src/main/java/com/keeper/homepage/domain/post/dto/response/PostDetailResponse.java
  src/main/java/com/keeper/homepage/domain/post/dto/response/PostResponse.java
  src/main/java/com/keeper/homepage/domain/post/dto/response/TempPostResponse.java
  src/main/java/com/keeper/homepage/domain/post/entity/Post.java
  src/main/java/com/keeper/homepage/domain/post/entity/embedded/PostContent.java
  src/main/java/com/keeper/homepage/domain/post/entity/embedded/PostStatus.java
  src/test/java/com/keeper/homepage/IntegrationTest.java
  src/test/java/com/keeper/homepage/domain/post/PostTestHelper.java
  src/test/java/com/keeper/homepage/domain/post/api/PostControllerTest.java
  src/test/java/com/keeper/homepage/domain/post/application/PostServiceTest.java
  src/test/java/com/keeper/homepage/domain/post/dao/PostRepositoryTest.java
Labels: 🛠️ refactor

#442 Feature/#398 하드코딩된 테스트 코드 수정
  src/test/java/com/keeper/homepage/domain/auth/api/test/AuthTestControllerTest.java
Labels: ✅ test, ⭐️ backend

#443 Feature/#422 PR에 CI 도입
  .github/workflows/check_pull_request.yml
Labels: 🚀 feature
