Repository KEEPER31337/Homepage-Back-R2, pull requests merged in 2024-02, with the labels that each got.

#402 Feature/#398 하드 코딩된 테스트 코드를 수정
  src/test/java/com/keeper/homepage/domain/auth/api/test/AuthTestControllerTest.java
  src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
Labels: 🐞 bug

#407 Feature/#146 리드미 작성
  CONTRIBUTING.md
  LICENSE
  README.md
  images/CICD.png
  images/ERD.png
  images/Infra.png
  images/logo_neon.svg
Labels: 📄 docs

#409 Feature/#408-JwtTokenFilter와_logout개선
  src/main/java/com/keeper/homepage/global/config/security/SecurityConfiguration.java
  src/main/java/com/keeper/homepage/global/config/security/filter/JwtAuthenticationFilter.java
  src/main/java/com/keeper/homepage/global/config/security/filter/RefreshTokenFilter.java
  src/main/java/com/keeper/homepage/global/config/security/filter/token_condition/AccessTokenReissueCondition.java
  src/main/java/com/keeper/homepage/global/config/security/filter/token_condition/JwtTokenCondition.java
  src/main/java/com/keeper/homepage/global/config/security/filter/token_condition/JwtTokenConditionFactory.java
  src/main/java/com/keeper/homepage/global/config/security/filter/token_condition/JwtTokenValidCondition.java
Labels: 🛠️ refactor

#411 Feature/#396 도서 관리 기능을 사서의 요구사항에 맞게 변경
  src/main/java/com/keeper/homepage/domain/library/application/BookService.java
  src/main/java/com/keeper/homepage/domain/library/dao/BookBorrowLogRepository.java
  src/main/java/com/keeper/homepage/global/error/ErrorCode.java
  src/test/java/com/keeper/homepage/domain/library/application/BookServiceTest.java
Labels: ✏️ chore, ⭐️ backend
